//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountEmailGadis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountEmailGadis()
        {
            this.OperatoriAccountEmail = new HashSet<OperatoriAccountEmail>();
            this.AreeGadis = new HashSet<AreeGadis>();
            this.Operatori = new HashSet<Operatori>();
            this.Operatori1 = new HashSet<Operatori>();
        }
    
        public int AccountEmailGadisID { get; set; }
        public string AccountEmailGadis1 { get; set; }
        public string Password { get; set; }
        public bool IsAccessibileInTurno { get; set; }
        public string Firma { get; set; }
        public string Username { get; set; }
        public string TipoAccount { get; set; }
        public bool FlagAttivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatoriAccountEmail> OperatoriAccountEmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreeGadis> AreeGadis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operatori> Operatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operatori> Operatori1 { get; set; }
    }
}
