//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreeAnno
    {
        public short AreaGadisID { get; set; }
        public int Anno { get; set; }
        public Nullable<double> Fatturato { get; set; }
        public Nullable<short> PraticheRegistrate { get; set; }
        public Nullable<short> PraticheOfferte { get; set; }
        public Nullable<short> PraticheOrdinate { get; set; }
        public Nullable<short> PraticheChiuse { get; set; }
        public Nullable<short> PraticheAnnullate { get; set; }
        public Nullable<short> NumTotViaggianti { get; set; }
        public Nullable<double> NumMedioViaggianti { get; set; }
        public Nullable<double> NumMedioGiorni { get; set; }
    }
}
