//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camere
    {
        public int FornitoreID { get; set; }
        public string CodTipoCamera { get; set; }
        public Nullable<short> Quantita { get; set; }
    
        public virtual FornitoriValutazioni FornitoriValutazioni { get; set; }
        public virtual TipiCamera TipiCamera { get; set; }
    }
}
