//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaratteristichePratica
    {
        public int AnnoPratica { get; set; }
        public int NumPratica { get; set; }
        public bool IsTargetLusso { get; set; }
        public bool IsTargetAlto { get; set; }
        public bool IsTargetMedioAlto { get; set; }
        public bool IsTargetMedio { get; set; }
        public bool IsTargetMedioBasso { get; set; }
    
        public virtual Pratiche Pratiche { get; set; }
    }
}
