//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaratteristicheStruttura
    {
        public int FornitoreID { get; set; }
        public bool FlagAccessoDisabili { get; set; }
        public bool FlagAccessoVetturePrivate { get; set; }
        public bool FlagAccettaCarteCredito { get; set; }
        public bool FlagAriaCondizionata { get; set; }
        public bool FlagAscensore { get; set; }
        public bool FlagBar { get; set; }
        public bool FlagBoutiqueHotel { get; set; }
        public bool FlagLavaturaBiancheria { get; set; }
        public bool FlagParcheggio { get; set; }
        public bool FlagRistorante { get; set; }
        public bool FlagRistoranteVegetariano { get; set; }
        public bool FlagTrasportoClienti { get; set; }
        public bool FlagAccessoMezziPubblici { get; set; }
        public bool FlagAccettaAnimaliDomestici { get; set; }
        public bool FlagAreaBimbi { get; set; }
        public bool FlagBocce { get; set; }
        public bool FlagCampoCalcetto { get; set; }
        public bool FlagCampoGolf { get; set; }
        public bool FlagCampoTennis { get; set; }
        public bool FlagCustodiaValori { get; set; }
        public bool FlagDiscoteca { get; set; }
        public bool FlagEquitazione { get; set; }
        public bool FlagFitnessCentroSalute { get; set; }
        public bool FlagGarage { get; set; }
        public bool FlagGiardino { get; set; }
        public bool FlagHall { get; set; }
        public bool FlagImpiantiTermaliPropri { get; set; }
        public bool FlagMeetingRoom { get; set; }
        public bool FlagMiniMarket { get; set; }
        public bool FlagMiniGolf { get; set; }
        public bool FlagPalestra { get; set; }
        public bool FlagPingPong { get; set; }
        public bool FlagPiscinaCoperta { get; set; }
        public bool FlagPiscinaScoperta { get; set; }
        public bool FlagPuliziaCalzature { get; set; }
        public bool FlagSalaConferenze { get; set; }
        public bool FlagSalaLetturaSeparata { get; set; }
        public bool FlagSalaTVSeparata { get; set; }
        public bool FlagSauna { get; set; }
        public bool FlagSciNautico { get; set; }
        public bool FlagServizioBabySitting { get; set; }
        public bool FlagServizioCongressi { get; set; }
        public bool FlagSolarium { get; set; }
        public bool FlagSpiaggiaRiservata { get; set; }
        public bool FlagTavernetta { get; set; }
        public bool FlagVela { get; set; }
        public bool FlagWellness { get; set; }
        public bool FlagWiFi { get; set; }
        public bool FlagWindsurf { get; set; }
    
        public virtual Fornitori Fornitori { get; set; }
    }
}
