//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaratteristicheFornitore
    {
        public int FornitoreID { get; set; }
        public bool IsTargetLusso { get; set; }
        public bool IsTargetAlto { get; set; }
        public bool IsTargetMedioAlto { get; set; }
        public bool IsTargetMedio { get; set; }
        public bool IsTargetMedioBasso { get; set; }
        public bool isAccettaAnimali { get; set; }
        public bool isAccessibileDisabili { get; set; }
        public Nullable<short> NumGiorniScadPreArrivoGruppo { get; set; }
        public Nullable<short> NumGiorniScadPostArrivoGruppo { get; set; }
        public bool IsFornitoreAlberghiero { get; set; }
        public bool IsLocalePubblico { get; set; }
        public bool IsGuida { get; set; }
        public bool IsFornitoreTrasporti { get; set; }
        public bool IsAltroTipoForn { get; set; }
        public string NoteSuCaratteristiche { get; set; }
    
        public virtual Fornitori Fornitori { get; set; }
    }
}
