//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaratteristicheServizio
    {
        public int ServizioID { get; set; }
        public int FornitoreID { get; set; }
        public bool IsTargetLusso { get; set; }
        public bool IsTargetAlto { get; set; }
        public bool IsTargetMedioAlto { get; set; }
        public bool IsTargetMedio { get; set; }
        public bool IsTargetMedioBasso { get; set; }
        public bool IsInclusoInRicerche { get; set; }
        public bool IsDescServizioInOfferta { get; set; }
        public bool IsImgServizioInOfferta { get; set; }
        public bool IsSupplementare { get; set; }
        public bool IsDescFornInOfferta { get; set; }
        public bool IsImgFornInOfferta { get; set; }
        public bool IsDescDestInOfferta { get; set; }
        public bool IsImgDestInOfferta { get; set; }
        public bool FlagDataOpzioneFornitore { get; set; }
        public bool FlagCheckUnGiornoPrima { get; set; }
        public bool FlagAmmetteValutazione { get; set; }
        public bool FlagStampaVoucher { get; set; }
        public bool FlagAmmetteTassaSoggiorno { get; set; }
        public bool FlagNonSoggettaACommissioni { get; set; }
        public bool FlagNecessariaListaNominativa { get; set; }
        public bool FlagNecessarioNumPax { get; set; }
        public bool FlagSoloPerSingola { get; set; }
        public bool FlagNomeFornInDocs { get; set; }
        public bool FlagIndirFornInDocs { get; set; }
        public bool FlagIndicaFornInDocs { get; set; }
        public bool FlagStampaInDayByDay { get; set; }
        public bool FlagCommissioniFornNettoIva { get; set; }
        public bool FlagZTL { get; set; }
        public bool FlagPrezzoDaGruppo { get; set; }
        public bool FlagDescrizioniDaGruppo { get; set; }
        public bool FlagImmaginiDaGruppo { get; set; }
        public bool FlagDayByDayDaGruppo { get; set; }
        public bool FlagNoteVoucherGruppo { get; set; }
        public bool FlagNoteVoucherFigli { get; set; }
    
        public virtual Servizi Servizi { get; set; }
    }
}
