//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaratteristicheCamere
    {
        public int FornitoreId { get; set; }
        public bool FlagAriaCondizionata { get; set; }
        public bool FlagInsonorizzazione { get; set; }
        public bool FlagRiscaldamento { get; set; }
        public bool FlagTelefono { get; set; }
        public bool FlagTelevisione { get; set; }
        public bool FlagBalcone { get; set; }
        public bool FlagVista { get; set; }
        public bool FlagCassaforte { get; set; }
        public bool FlagWiFi { get; set; }
        public bool FlagDoccia { get; set; }
        public bool FlagFrigoBar { get; set; }
        public bool FlagIdromassaggio { get; set; }
        public bool FlagRadio { get; set; }
        public bool FlagVasca { get; set; }
    
        public virtual Fornitori Fornitori { get; set; }
    }
}
