//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clienti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clienti()
        {
            this.Clienti1 = new HashSet<Clienti>();
            this.Clienti11 = new HashSet<Clienti>();
            this.Clienti12 = new HashSet<Clienti>();
            this.ClientiTipiCamera = new HashSet<ClientiTipiCamera>();
            this.ClientiCondizioniPagamento = new HashSet<ClientiCondizioniPagamento>();
            this.Contatti = new HashSet<Contatti>();
            this.ContattiCliente = new HashSet<ContattiCliente>();
            this.Documenti = new HashSet<Documenti>();
            this.Documenti1 = new HashSet<Documenti>();
            this.FattureClienti = new HashSet<FattureClienti>();
            this.Lamentele = new HashSet<Lamentele>();
            this.MessaggiDestinatari = new HashSet<MessaggiDestinatari>();
            this.Messaggi = new HashSet<Messaggi>();
            this.Note = new HashSet<Note>();
            this.PagamentiRicevutiRighe = new HashSet<PagamentiRicevutiRighe>();
            this.Pratiche = new HashSet<Pratiche>();
            this.Pratiche1 = new HashSet<Pratiche>();
            this.Pratiche2 = new HashSet<Pratiche>();
            this.PratichePagamentiCliente = new HashSet<PratichePagamentiCliente>();
            this.Scadenze = new HashSet<Scadenze>();
            this.UsiDocumento = new HashSet<UsiDocumento>();
            this.UsiStringa = new HashSet<UsiStringa>();
            this.SegmentiMarketing = new HashSet<SegmentiMarketing>();
            this.TipiAttivita = new HashSet<TipiAttivita>();
        }
    
        public int ClienteID { get; set; }
        public string RagioneSociale { get; set; }
        public string RagioneSocialeDocumenti { get; set; }
        public string ResponsabileDiDefault { get; set; }
        public string NoteSulCliente { get; set; }
        public string NoteClientePerPratica { get; set; }
        public string NoteContatti { get; set; }
        public string NoteVendite { get; set; }
        public string NoteContabili { get; set; }
        public string CodiceFiscale { get; set; }
        public string PartitaIva { get; set; }
        public string Indirizzo { get; set; }
        public string IdClienteAdhoc { get; set; }
        public Nullable<int> IntermediarioID { get; set; }
        public Nullable<double> PercCommissioneIntermediario { get; set; }
        public bool FlagAttivo { get; set; }
        public Nullable<int> ContattoID { get; set; }
        public string CodicePostale { get; set; }
        public string Localita { get; set; }
        public Nullable<short> ProvinciaID { get; set; }
        public string Provincia { get; set; }
        public string Internet { get; set; }
        public string SitoWeb2 { get; set; }
        public Nullable<short> OrigineClienteID { get; set; }
        public string ResponsabileContabilita { get; set; }
        public Nullable<short> NazioneId { get; set; }
        public Nullable<short> Valuta { get; set; }
        public Nullable<short> CodiceLingua { get; set; }
        public Nullable<System.DateTime> DataLavoro { get; set; }
        public string CodiceBanca { get; set; }
        public Nullable<int> ClienteFatturazioneID { get; set; }
        public Nullable<int> ClienteCapogruppoID { get; set; }
        public string GratuitaID { get; set; }
        public string OperatoreID { get; set; }
        public bool HaLamentele { get; set; }
        public Nullable<short> NumGiorniScadenzaReleaseCliente { get; set; }
        public Nullable<double> MargineTarget { get; set; }
        public Nullable<int> FatturatoGadisEuro { get; set; }
        public Nullable<short> NumCollaboratori { get; set; }
        public System.DateTime DataInserimento { get; set; }
        public string OperUltAgg { get; set; }
        public System.DateTime DataUltAgg { get; set; }
        public Nullable<int> IdFornitoreIntermediario { get; set; }
    
        public virtual Banche Banche { get; set; }
        public virtual CaratteristicheCliente CaratteristicheCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clienti> Clienti1 { get; set; }
        public virtual Clienti Clienti2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clienti> Clienti11 { get; set; }
        public virtual Clienti Clienti3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clienti> Clienti12 { get; set; }
        public virtual Clienti Clienti4 { get; set; }
        public virtual Fornitori Fornitori { get; set; }
        public virtual Gratuita Gratuita { get; set; }
        public virtual Lingue Lingue { get; set; }
        public virtual Nazioni Nazioni { get; set; }
        public virtual Operatori Operatori { get; set; }
        public virtual OriginiClienti OriginiClienti { get; set; }
        public virtual Province Province { get; set; }
        public virtual ClientiArchivioNote ClientiArchivioNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientiTipiCamera> ClientiTipiCamera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientiCondizioniPagamento> ClientiCondizioniPagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contatti> Contatti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContattiCliente> ContattiCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documenti> Documenti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documenti> Documenti1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FattureClienti> FattureClienti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lamentele> Lamentele { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessaggiDestinatari> MessaggiDestinatari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Messaggi> Messaggi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Note { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagamentiRicevutiRighe> PagamentiRicevutiRighe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pratiche> Pratiche { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pratiche> Pratiche1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pratiche> Pratiche2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PratichePagamentiCliente> PratichePagamentiCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scadenze> Scadenze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsiDocumento> UsiDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsiStringa> UsiStringa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentiMarketing> SegmentiMarketing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipiAttivita> TipiAttivita { get; set; }
    }
}
