//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientiArchivioNote
    {
        public int ClienteID { get; set; }
        public string NoteSulCliente { get; set; }
        public string NoteClientePerPratica { get; set; }
        public string NoteContatti { get; set; }
        public string NoteVendite { get; set; }
        public string NoteContabili { get; set; }
        public Nullable<System.DateTime> DataUltAgg { get; set; }
    
        public virtual Clienti Clienti { get; set; }
    }
}
