//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientiAnnoSegmentiMarketing
    {
        public int ClienteID { get; set; }
        public int Anno { get; set; }
        public short SegmentoMarketingID { get; set; }
        public Nullable<short> NumPratiche { get; set; }
        public Nullable<double> Perc { get; set; }
    }
}
