//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollezioniImmagini
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollezioniImmagini()
        {
            this.Immagini = new HashSet<Immagini>();
        }
    
        public short CollezioneID { get; set; }
        public string Titolo { get; set; }
        public System.DateTime DataInserimento { get; set; }
        public string OperatoreID { get; set; }
        public string Fonte { get; set; }
        public string Copyright { get; set; }
        public Nullable<int> DestinazioneID { get; set; }
        public Nullable<int> FornitoreID { get; set; }
    
        public virtual Destinazioni Destinazioni { get; set; }
        public virtual Fornitori Fornitori { get; set; }
        public virtual Operatori Operatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Immagini> Immagini { get; set; }
    }
}
