//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComuniAnagrafe
    {
        public string codice { get; set; }
        public string nome { get; set; }
        public string zonacodice { get; set; }
        public string zonanome { get; set; }
        public string regionecodice { get; set; }
        public string regionenome { get; set; }
        public string provinciacodice { get; set; }
        public string provincianome { get; set; }
        public string provinciasigla { get; set; }
        public string codicecatastale { get; set; }
        public Nullable<int> popolazione { get; set; }
        public string nazione { get; set; }
    }
}
