//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContattiFornitore
    {
        public int FornitoreID { get; set; }
        public short ContattoFornitoreID { get; set; }
        public string Tipo { get; set; }
        public string Titolo { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string Descrizione { get; set; }
        public string Ruolo { get; set; }
        public string Note { get; set; }
        public string EstremiIndirizzo { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public bool IsResponsabileOfferte { get; set; }
        public bool IsResponsabileOperativo { get; set; }
        public bool IsResponsabileContabile { get; set; }
        public bool IsDestinatarioMailing { get; set; }
        public bool IsConsenzienteGDPR { get; set; }
        public Nullable<System.DateTime> DataConsensoGDPR { get; set; }
        public bool IsAttivo { get; set; }
        public bool IsPreferito { get; set; }
        public bool IsDirezione { get; set; }
        public bool FlagTelefonoSuVoucher { get; set; }
        public bool FlagMobileSuVoucher { get; set; }
    
        public virtual Fornitori Fornitori { get; set; }
    }
}
