//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contatti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contatti()
        {
            this.Opportunita = new HashSet<Opportunita>();
        }
    
        public int ContattoID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Operatore { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public string Note { get; set; }
        public string CanaleID { get; set; }
        public string DatiCliente { get; set; }
        public Nullable<short> ManifestazioneID { get; set; }
        public string RiferimentoCliente { get; set; }
        public string Persona { get; set; }
    
        public virtual Canali Canali { get; set; }
        public virtual Clienti Clienti { get; set; }
        public virtual Manifestazioni Manifestazioni { get; set; }
        public virtual Operatori Operatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opportunita> Opportunita { get; set; }
    }
}
