//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateAggiuntivePerSerie
    {
        public int AnnoPratica { get; set; }
        public int NumPratica { get; set; }
        public short DateAggiuntivePerSerieID { get; set; }
        public System.DateTime Dal { get; set; }
        public System.DateTime Al { get; set; }
        public string Note { get; set; }
    
        public virtual Pratiche Pratiche { get; set; }
    }
}
