//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinazioniImport
    {
        public string CodiceGO5 { get; set; }
        public string DescrizioneGo5 { get; set; }
        public bool FlagAttiva { get; set; }
        public string SostituitoDa { get; set; }
        public string Livello { get; set; }
        public string OldDest { get; set; }
        public string OldZona { get; set; }
        public string CodStat { get; set; }
        public bool FlagDestinazionePratica { get; set; }
        public bool FlagDestinazioneStatistica { get; set; }
        public string Provenienza { get; set; }
        public Nullable<int> Nazione { get; set; }
        public Nullable<short> CodiceAreaGadis { get; set; }
        public bool FlagSenzaTassaSoggiorno { get; set; }
        public string Figlio_di { get; set; }
    }
}
