//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destinazioni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Destinazioni()
        {
            this.CollezioniImmagini = new HashSet<CollezioniImmagini>();
            this.Destinazioni1 = new HashSet<Destinazioni>();
            this.Documenti = new HashSet<Documenti>();
            this.Fornitori = new HashSet<Fornitori>();
            this.Fornitori1 = new HashSet<Fornitori>();
            this.Lamentele = new HashSet<Lamentele>();
            this.Note = new HashSet<Note>();
            this.Opportunita = new HashSet<Opportunita>();
            this.Pratiche = new HashSet<Pratiche>();
            this.PuntiDestinazione = new HashSet<PuntiDestinazione>();
            this.Regioni1 = new HashSet<Regioni>();
            this.Servizi = new HashSet<Servizi>();
            this.Servizi_TEMP = new HashSet<Servizi_TEMP>();
            this.Servizi2 = new HashSet<Servizi2>();
            this.UsiDocumento = new HashSet<UsiDocumento>();
            this.UsiImmagine = new HashSet<UsiImmagine>();
            this.UsiStringa = new HashSet<UsiStringa>();
            this.Destinazioni11 = new HashSet<Destinazioni>();
            this.Destinazioni3 = new HashSet<Destinazioni>();
        }
    
        public int DestinazioneID { get; set; }
        public string Nome { get; set; }
        public Nullable<long> NomeDocumentiStringa { get; set; }
        public Nullable<long> SottotitoloDocumentiStringa { get; set; }
        public Nullable<long> DescrizioneBreveStringa { get; set; }
        public Nullable<long> DescrizioneLogisticaStringa { get; set; }
        public Nullable<decimal> Latitudine { get; set; }
        public Nullable<decimal> Longitudine { get; set; }
        public Nullable<short> CodiceAreaGadis { get; set; }
        public short IdLivello { get; set; }
        public Nullable<short> Nazione { get; set; }
        public string CodiceRegioneIstat { get; set; }
        public Nullable<short> RegioneID { get; set; }
        public string Cap { get; set; }
        public string CodiceCittaMetropolitanaIstat { get; set; }
        public string CodiceProvinciaIstat { get; set; }
        public string Provincia { get; set; }
        public string CodiceComuneCatastale { get; set; }
        public string CodiceComuneIstat { get; set; }
        public string CodiceZonaOld { get; set; }
        public string CodiceDestinazioneOld { get; set; }
        public string CodiceComuneOld { get; set; }
        public string Provenienza { get; set; }
        public string Sostituito_da { get; set; }
        public string CodDestinazioneStatistica { get; set; }
        public bool IsSenzaTassaSoggiorno { get; set; }
        public bool IsDestinazionePratiche { get; set; }
        public bool FlagAttiva { get; set; }
        public bool IsDescDaCompletare { get; set; }
        public Nullable<short> ProvinciaID { get; set; }
        public bool IsDestinazioneStatistica { get; set; }
        public Nullable<int> IdDestinazioneStatistica { get; set; }
        public string NoteInterne { get; set; }
        public Nullable<short> TassaSoggiornoID { get; set; }
        public bool FlagZTL { get; set; }
        public Nullable<long> TestoZTL { get; set; }
        public string CodiceDestinazioneGadis { get; set; }
        public Nullable<int> AnnoUltimaPratica { get; set; }
        public Nullable<int> NumUltimaPratica { get; set; }
        public Nullable<System.DateTime> DataUltimaPratica { get; set; }
        public string OperUltAgg { get; set; }
        public System.DateTime DataUltAgg { get; set; }
        public string SitoWebZTL { get; set; }
        public Nullable<System.DateTime> DataAggZTL { get; set; }
    
        public virtual AreeGadis AreeGadis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollezioniImmagini> CollezioniImmagini { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Destinazioni> Destinazioni1 { get; set; }
        public virtual Destinazioni Destinazioni2 { get; set; }
        public virtual LivelliDestinazione LivelliDestinazione { get; set; }
        public virtual Nazioni Nazioni { get; set; }
        public virtual Operatori Operatori { get; set; }
        public virtual Province Province { get; set; }
        public virtual Regioni Regioni { get; set; }
        public virtual Stringhe Stringhe { get; set; }
        public virtual TasseSoggiorno TasseSoggiorno { get; set; }
        public virtual Stringhe Stringhe1 { get; set; }
        public virtual Stringhe Stringhe2 { get; set; }
        public virtual Stringhe Stringhe3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documenti> Documenti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fornitori> Fornitori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fornitori> Fornitori1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lamentele> Lamentele { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Note { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opportunita> Opportunita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pratiche> Pratiche { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuntiDestinazione> PuntiDestinazione { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Regioni> Regioni1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servizi> Servizi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servizi_TEMP> Servizi_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servizi2> Servizi2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsiDocumento> UsiDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsiImmagine> UsiImmagine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsiStringa> UsiStringa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Destinazioni> Destinazioni11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Destinazioni> Destinazioni3 { get; set; }
    }
}
