//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DettagliFornitori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DettagliFornitori()
        {
            this.FornitoriDettagli = new HashSet<FornitoriDettagli>();
        }
    
        public short DettaglioID { get; set; }
        public string Nome { get; set; }
        public string Sigla { get; set; }
        public bool FlagQta { get; set; }
        public bool FlagDaEsporreInOfferta { get; set; }
        public Nullable<int> StringaID { get; set; }
        public bool FlagPerAlberghiero { get; set; }
        public bool FlagPerLocaliPubblici { get; set; }
        public bool FlagPerGuide { get; set; }
        public bool FlagPerTrasporti { get; set; }
        public bool FlagPerAltro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornitoriDettagli> FornitoriDettagli { get; set; }
    }
}
