//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documenti()
        {
            this.FeedbackCliente = new HashSet<FeedbackCliente>();
            this.PratichePagamentiFornitori = new HashSet<PratichePagamentiFornitori>();
            this.Messaggi = new HashSet<Messaggi>();
        }
    
        public int DocumentoID { get; set; }
        public string Titolo { get; set; }
        public string NomeFile { get; set; }
        public Nullable<short> TipoDocumentoID { get; set; }
        public Nullable<short> ModelloDocumentoID { get; set; }
        public Nullable<System.DateTime> DataDocumento { get; set; }
        public bool FlagVisibileSuInternet { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> DataScadenzaVisibilitaInternet { get; set; }
        public Nullable<System.DateTime> DataArchiviazione { get; set; }
        public string Note { get; set; }
        public string Percorso { get; set; }
        public string Operatore { get; set; }
        public string Fonte { get; set; }
        public string Copyright { get; set; }
        public string Tags { get; set; }
        public string Metadati { get; set; }
        public Nullable<int> FornitoreDestinatarioID { get; set; }
        public Nullable<int> ClienteDestinatarioID { get; set; }
        public string PercorsoPDF { get; set; }
        public bool FlagDocRicevuto { get; set; }
        public Nullable<int> ClienteAutoreID { get; set; }
        public Nullable<int> FornitoreAutoreID { get; set; }
        public Nullable<int> ServizioID { get; set; }
        public Nullable<int> DestinazioneID { get; set; }
        public Nullable<int> AnnoPratica { get; set; }
        public Nullable<int> NumPratica { get; set; }
        public Nullable<short> NumOfferta { get; set; }
    
        public virtual Clienti Clienti { get; set; }
        public virtual Clienti Clienti1 { get; set; }
        public virtual Destinazioni Destinazioni { get; set; }
        public virtual Fornitori Fornitori { get; set; }
        public virtual Fornitori Fornitori1 { get; set; }
        public virtual Offerte Offerte { get; set; }
        public virtual Operatori Operatori { get; set; }
        public virtual Pratiche Pratiche { get; set; }
        public virtual Servizi Servizi { get; set; }
        public virtual TipiDocumento TipiDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedbackCliente> FeedbackCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PratichePagamentiFornitori> PratichePagamentiFornitori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Messaggi> Messaggi { get; set; }
    }
}
