//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementiOffertaTipiCamera
    {
        public int AnnoPratica { get; set; }
        public int NumPratica { get; set; }
        public short NumOfferta { get; set; }
        public short NumSezione { get; set; }
        public short ElementoOffertaID { get; set; }
        public string CodTipoCamera { get; set; }
        public Nullable<short> Quantità { get; set; }
        public Nullable<System.DateTime> DataOpzioneFornitore { get; set; }
        public Nullable<System.DateTime> DataOpzioneCliente { get; set; }
    
        public virtual ElementiOfferta ElementiOfferta { get; set; }
        public virtual TipiCamera TipiCamera { get; set; }
    }
}
