//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementiOrdine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElementiOrdine()
        {
            this.ElementiOrdineTipiCamera = new HashSet<ElementiOrdineTipiCamera>();
            this.GiornateOrdinePosiz = new HashSet<GiornateOrdinePosiz>();
            this.Scadenze = new HashSet<Scadenze>();
            this.UsiImmagine = new HashSet<UsiImmagine>();
        }
    
        public int AnnoPratica { get; set; }
        public int NumPratica { get; set; }
        public short NumSezione { get; set; }
        public short ElementoOrdineID { get; set; }
        public string CodSequenza { get; set; }
        public Nullable<System.DateTime> DataInvioRichDisp { get; set; }
        public Nullable<System.DateTime> DataNostraConferma { get; set; }
        public bool FlagAttivo { get; set; }
        public Nullable<System.DateTime> DataOpzioneFornitore { get; set; }
        public Nullable<short> ElementoOrdineMasterID { get; set; }
        public Nullable<System.DateTime> DataVostraConferma { get; set; }
        public Nullable<double> PrezzoAcquistoLordo { get; set; }
        public Nullable<System.DateTime> DataReleaseFornitore { get; set; }
        public Nullable<System.DateTime> DataAnnullamento { get; set; }
        public Nullable<double> PrezzoAcquistoScorporatoIva { get; set; }
        public bool IsDaNonFatturareACliente { get; set; }
        public Nullable<double> PrezzoAcquisto { get; set; }
        public Nullable<double> PrezzoVendita { get; set; }
        public Nullable<short> Stato { get; set; }
        public Nullable<System.DateTime> DataDa { get; set; }
        public Nullable<System.DateTime> DataA { get; set; }
        public Nullable<System.TimeSpan> OrarioInizio { get; set; }
        public string NoteVoucherCliente { get; set; }
        public string NoteVoucherFornitore { get; set; }
        public Nullable<short> PaxDa { get; set; }
        public Nullable<short> PaxA { get; set; }
        public string NoteInterne { get; set; }
        public string TipoPrezzoAcquisto { get; set; }
        public string TipoPrezzoVendita { get; set; }
        public int FornitoreID { get; set; }
        public Nullable<int> FornitoreIntermediarioID { get; set; }
        public Nullable<int> FornitoreFatturanteID { get; set; }
        public int ServizioID { get; set; }
        public Nullable<short> Moltiplicatore { get; set; }
        public Nullable<short> PaxLimite { get; set; }
        public Nullable<double> IncrementoUnitarioAcquisto { get; set; }
        public Nullable<double> IncrementoUnitarioVendita { get; set; }
        public Nullable<short> DivisoreAcquisto { get; set; }
        public Nullable<short> DivisoreVendita { get; set; }
        public Nullable<short> AliquotaIva { get; set; }
        public Nullable<double> PercCommissione { get; set; }
        public Nullable<short> AliquotaIvaSuCommissione { get; set; }
        public Nullable<short> DurataInOre { get; set; }
        public Nullable<short> NumMezziNecessari { get; set; }
        public Nullable<short> VariantePrezzoID { get; set; }
        public Nullable<int> AnnoVariantePrezzo { get; set; }
        public Nullable<short> NumPagantiAcq { get; set; }
        public Nullable<short> NumGratuitaAcq { get; set; }
        public Nullable<short> QtaTotAcq { get; set; }
        public Nullable<double> PrezzoTotAcq { get; set; }
        public Nullable<short> NumPagantiVen { get; set; }
        public Nullable<short> NumGratuitaVen { get; set; }
        public Nullable<short> QtaTotVen { get; set; }
        public Nullable<double> PrezzoTotVen { get; set; }
        public string GratuitaID { get; set; }
        public bool FlagContingenteComePratica { get; set; }
        public bool FlagDataOpzioneFornitore { get; set; }
        public bool FlagCheckUnGiornoPrima { get; set; }
        public bool FlagAmmetteValutazione { get; set; }
        public bool FlagStampaVoucher { get; set; }
        public bool FlagAmmetteTassaSoggiorno { get; set; }
        public bool FlagNonSoggettaACommissioni { get; set; }
        public bool FlagNecessariaRoomingList { get; set; }
        public bool FlagNecessarioNumPax { get; set; }
        public bool FlagSoloPerSingola { get; set; }
        public bool FlagNomeFornInDocs { get; set; }
        public bool FlagIndirFornInDocs { get; set; }
        public bool FlagIndicaFornInDocs { get; set; }
        public bool FlagStampaInDayByDay { get; set; }
        public bool FlagCommissioniFornNettoIva { get; set; }
        public bool FlagServizioNascosto { get; set; }
        public Nullable<short> FeedbackOperatore { get; set; }
        public Nullable<System.DateTime> DataFeedbackOperatore { get; set; }
        public string OperatoreAutoreFeedback { get; set; }
        public bool FlagServizioFacoltativoEffettuato { get; set; }
        public Nullable<short> NumPaxEffettivi { get; set; }
        public Nullable<double> CommissioneUnitariaForn { get; set; }
        public string LocalitaGO2 { get; set; }
        public string DescServizio { get; set; }
        public string DescFornitore { get; set; }
        public string DescDestinazione { get; set; }
        public bool FlagDescFornInDocs { get; set; }
        public bool FlagFotoFornInDocs { get; set; }
        public bool FlagDescServInDocs { get; set; }
        public bool FlagFotoServInDocs { get; set; }
        public bool FlagDescDestInDocs { get; set; }
        public bool FlagFotoDestInDocs { get; set; }
        public string RiferimentiSuProgramma { get; set; }
        public Nullable<short> NumMezziNecessariVen { get; set; }
        public bool FlagUsaPostiMezzoInVendita { get; set; }
        public Nullable<short> RifElementoSplittatoID { get; set; }
        public bool FlagSplittato { get; set; }
        public Nullable<short> DiCui { get; set; }
        public bool FlagNoteVoucherComplete { get; set; }
    
        public virtual Fornitori Fornitori { get; set; }
        public virtual Fornitori Fornitori1 { get; set; }
        public virtual Gratuita Gratuita { get; set; }
        public virtual Iva Iva { get; set; }
        public virtual Iva Iva1 { get; set; }
        public virtual Servizi Servizi { get; set; }
        public virtual SezioniOrdine SezioniOrdine { get; set; }
        public virtual StatiElementoOrdine StatiElementoOrdine { get; set; }
        public virtual VariantiPrezziServizioFornitoreAnno VariantiPrezziServizioFornitoreAnno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementiOrdineTipiCamera> ElementiOrdineTipiCamera { get; set; }
        public virtual FeedbackClienteServizi FeedbackClienteServizi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiornateOrdinePosiz> GiornateOrdinePosiz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scadenze> Scadenze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsiImmagine> UsiImmagine { get; set; }
    }
}
