//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackClienteServizi
    {
        public int AnnoPratica { get; set; }
        public int NumPratica { get; set; }
        public short NumSezione { get; set; }
        public short ElementoOrdineID { get; set; }
        public Nullable<short> Feedback { get; set; }
    
        public virtual ElementiOrdine ElementiOrdine { get; set; }
        public virtual FeedbackCliente FeedbackCliente { get; set; }
    }
}
