//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FornitoriDettagli
    {
        public int FornitoreID { get; set; }
        public short DettaglioID { get; set; }
        public Nullable<double> Qta { get; set; }
    
        public virtual DettagliFornitori DettagliFornitori { get; set; }
        public virtual Fornitori Fornitori { get; set; }
    }
}
