//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FornitoriLocaliPubblici
    {
        public int LocalePubblicoID { get; set; }
        public Nullable<short> Posti { get; set; }
        public string Posizione { get; set; }
        public string Distanze { get; set; }
        public Nullable<System.DateTime> Ultimavisita { get; set; }
        public string OperatoreID { get; set; }
    
        public virtual Fornitori Fornitori { get; set; }
    }
}
