//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FornitoriValutazioni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FornitoriValutazioni()
        {
            this.Camere = new HashSet<Camere>();
            this.DisponibilitaFornitore = new HashSet<DisponibilitaFornitore>();
        }
    
        public int FornitoreID { get; set; }
        public Nullable<int> AnnoUltimaRistrutturazione { get; set; }
        public string Posizione { get; set; }
        public string Distanze { get; set; }
        public string DescrizioneCamere { get; set; }
        public string Servizi { get; set; }
        public string NotePrezzi { get; set; }
        public Nullable<short> NumCamere { get; set; }
        public Nullable<short> NumCoperti { get; set; }
        public Nullable<System.DateTime> UltimaVisita { get; set; }
        public string OperatoreID { get; set; }
        public string Valutatore { get; set; }
        public string ValutazPulizia { get; set; }
        public string ValutazDisponibilitaProprietari { get; set; }
        public string ValutazCucinaE1aColazione { get; set; }
        public string ValutazEsterno { get; set; }
        public string ValutazHall { get; set; }
        public string ValutazCamere { get; set; }
        public string ValutazAltriServizi { get; set; }
        public string ValutazRistorante { get; set; }
        public string ValutazBar { get; set; }
        public Nullable<short> NumStelle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Camere> Camere { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisponibilitaFornitore> DisponibilitaFornitore { get; set; }
        public virtual Fornitori Fornitori { get; set; }
        public virtual Operatori Operatori { get; set; }
    }
}
