//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornitori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fornitori()
        {
            this.Clienti = new HashSet<Clienti>();
            this.CollezioniImmagini = new HashSet<CollezioniImmagini>();
            this.ContattiFornitore = new HashSet<ContattiFornitore>();
            this.Documenti = new HashSet<Documenti>();
            this.Documenti1 = new HashSet<Documenti>();
            this.ElementiOfferta = new HashSet<ElementiOfferta>();
            this.ElementiOfferta1 = new HashSet<ElementiOfferta>();
            this.ElementiOrdine = new HashSet<ElementiOrdine>();
            this.ElementiOrdine1 = new HashSet<ElementiOrdine>();
            this.FattureFornitori = new HashSet<FattureFornitori>();
            this.FornitoriCondizioniPagamento = new HashSet<FornitoriCondizioniPagamento>();
            this.Fornitori1 = new HashSet<Fornitori>();
            this.Fornitori11 = new HashSet<Fornitori>();
            this.Fornitori12 = new HashSet<Fornitori>();
            this.FornitoriDettagli = new HashSet<FornitoriDettagli>();
            this.Lamentele = new HashSet<Lamentele>();
            this.MessaggiDestinatari = new HashSet<MessaggiDestinatari>();
            this.Messaggi = new HashSet<Messaggi>();
            this.PratichePagamentiFornitori = new HashSet<PratichePagamentiFornitori>();
            this.RichForn = new HashSet<RichForn>();
            this.RiferimentiFornitore = new HashSet<RiferimentiFornitore>();
            this.Scadenze = new HashSet<Scadenze>();
            this.Servizi = new HashSet<Servizi>();
            this.Servizi_TEMP = new HashSet<Servizi_TEMP>();
            this.Servizi2 = new HashSet<Servizi2>();
            this.Servizi1 = new HashSet<Servizi>();
            this.Servizi_TEMP1 = new HashSet<Servizi_TEMP>();
            this.Servizi21 = new HashSet<Servizi2>();
            this.UsiDocumento = new HashSet<UsiDocumento>();
            this.UsiImmagine = new HashSet<UsiImmagine>();
            this.UsiStringa = new HashSet<UsiStringa>();
            this.Lingue = new HashSet<Lingue>();
            this.SegmentiMarketing = new HashSet<SegmentiMarketing>();
            this.TipiFornitore = new HashSet<TipiFornitore>();
        }
    
        public int FornitoreID { get; set; }
        public string RagioneSociale { get; set; }
        public string RagioneSocialePerDocumenti { get; set; }
        public string NomeInternoFornitore { get; set; }
        public string Responsabile { get; set; }
        public string CodiceFiscale { get; set; }
        public string PartitaIva { get; set; }
        public string Indirizzo { get; set; }
        public Nullable<int> ComuneDestinazioneID { get; set; }
        public Nullable<int> LocalitaDestinazioneID { get; set; }
        public string CodicePostale { get; set; }
        public string Sitoweb { get; set; }
        public string Sitoweb2 { get; set; }
        public string NoteContabili { get; set; }
        public string CodFornitoreContabilita { get; set; }
        public Nullable<long> Descrizione { get; set; }
        public Nullable<long> DescrizioneLogistica { get; set; }
        public bool FlagAttivo { get; set; }
        public Nullable<short> CodiceLingua { get; set; }
        public string DatiBancari { get; set; }
        public string NotePerPratica { get; set; }
        public string NoteInterne { get; set; }
        public Nullable<System.DateTime> DataLavoro { get; set; }
        public string OperatoreCreazione { get; set; }
        public Nullable<int> GruppoFornitoreID { get; set; }
        public Nullable<short> Giudizio { get; set; }
        public Nullable<int> IntermediarioID { get; set; }
        public Nullable<int> FornitoreFatturazioneID { get; set; }
        public Nullable<short> Valuta { get; set; }
        public string GratuitaID { get; set; }
        public Nullable<short> NumGiorniScadenzaReleaseFornitore { get; set; }
        public bool HaLamentele { get; set; }
        public string StatoGDPR { get; set; }
        public Nullable<System.DateTime> DataContrattoGDPR { get; set; }
        public string CodTipoFornitoreGo2 { get; set; }
        public string LocalitaNonConforme { get; set; }
        public Nullable<int> AnnoUltimaPratica { get; set; }
        public Nullable<int> NumUltimaPratica { get; set; }
        public Nullable<System.DateTime> DataUltimaPratica { get; set; }
        public string OperUltAgg { get; set; }
        public System.DateTime DataUltAgg { get; set; }
        public string CodSDI { get; set; }
        public string IndirizzoPEC { get; set; }
        public Nullable<int> ZonaDestinazioneID { get; set; }
    
        public virtual CaratteristicheCamere CaratteristicheCamere { get; set; }
        public virtual CaratteristicheFornitore CaratteristicheFornitore { get; set; }
        public virtual CaratteristicheStruttura CaratteristicheStruttura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clienti> Clienti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollezioniImmagini> CollezioniImmagini { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContattiFornitore> ContattiFornitore { get; set; }
        public virtual Destinazioni Destinazioni { get; set; }
        public virtual Destinazioni Destinazioni1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documenti> Documenti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documenti> Documenti1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementiOfferta> ElementiOfferta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementiOfferta> ElementiOfferta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementiOrdine> ElementiOrdine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementiOrdine> ElementiOrdine1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FattureFornitori> FattureFornitori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornitoriCondizioniPagamento> FornitoriCondizioniPagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fornitori> Fornitori1 { get; set; }
        public virtual Fornitori Fornitori2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fornitori> Fornitori11 { get; set; }
        public virtual Fornitori Fornitori3 { get; set; }
        public virtual Gratuita Gratuita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fornitori> Fornitori12 { get; set; }
        public virtual Fornitori Fornitori4 { get; set; }
        public virtual Operatori Operatori { get; set; }
        public virtual Operatori Operatori1 { get; set; }
        public virtual Pratiche Pratiche { get; set; }
        public virtual Stringhe Stringhe { get; set; }
        public virtual Stringhe Stringhe1 { get; set; }
        public virtual Valute Valute { get; set; }
        public virtual FornitoriArchivioNote FornitoriArchivioNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornitoriDettagli> FornitoriDettagli { get; set; }
        public virtual FornitoriValutazioni FornitoriValutazioni { get; set; }
        public virtual FornitoriGuideAccompagnatori FornitoriGuideAccompagnatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lamentele> Lamentele { get; set; }
        public virtual FornitoriLocaliPubblici FornitoriLocaliPubblici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessaggiDestinatari> MessaggiDestinatari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Messaggi> Messaggi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PratichePagamentiFornitori> PratichePagamentiFornitori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RichForn> RichForn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiferimentiFornitore> RiferimentiFornitore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scadenze> Scadenze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servizi> Servizi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servizi_TEMP> Servizi_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servizi2> Servizi2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servizi> Servizi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servizi_TEMP> Servizi_TEMP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servizi2> Servizi21 { get; set; }
        public virtual FornitoriTrasportatori FornitoriTrasportatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsiDocumento> UsiDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsiImmagine> UsiImmagine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsiStringa> UsiStringa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lingue> Lingue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentiMarketing> SegmentiMarketing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipiFornitore> TipiFornitore { get; set; }
    }
}
