//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FornitoriCondizioniPagamento
    {
        public int FornitoreID { get; set; }
        public short Progressivo { get; set; }
        public Nullable<short> TipoPagamentoID { get; set; }
        public Nullable<double> Perc { get; set; }
        public bool FlagAcconto { get; set; }
        public Nullable<short> CodEvento { get; set; }
        public Nullable<short> Giorni { get; set; }
        public bool FlagGiorniPrima { get; set; }
        public Nullable<short> CodMezzoPagamento { get; set; }
        public string CodPagamentoOld { get; set; }
    
        public virtual CondizioniPagamento CondizioniPagamento { get; set; }
        public virtual Eventi Eventi { get; set; }
        public virtual Fornitori Fornitori { get; set; }
        public virtual MezziPagamento MezziPagamento { get; set; }
    }
}
