//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunzioniGO
    {
        public long id { get; set; }
        public string Form { get; set; }
        public string SiglaFunzione { get; set; }
        public string NomeFunzione { get; set; }
        public bool IsLink { get; set; }
    
        public virtual Funzioni Funzioni { get; set; }
    }
}
