//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funzioni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funzioni()
        {
            this.FunzioniGO = new HashSet<FunzioniGO>();
            this.OperatoriFunzioni = new HashSet<OperatoriFunzioni>();
            this.Log = new HashSet<Log>();
        }
    
        public string Sigla { get; set; }
        public string Descrizione { get; set; }
        public Nullable<short> IdModulo { get; set; }
        public bool IsToBeLogged { get; set; }
        public Nullable<byte> LivelloAbilitazioniOperatore { get; set; }
        public Nullable<byte> LivelloAbilitazioniCapoArea { get; set; }
        public Nullable<byte> LivelloAbilitazioniSuperUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FunzioniGO> FunzioniGO { get; set; }
        public virtual Moduli Moduli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatoriFunzioni> OperatoriFunzioni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Log { get; set; }
    }
}
