//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GadisOfficeBaseVuota1705_ProdEntities : DbContext
    {
        public GadisOfficeBaseVuota1705_ProdEntities()
            : base("name=GadisOfficeBaseVuota1705_ProdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountEmailGadis> AccountEmailGadis { get; set; }
        public virtual DbSet<AliasAccountGadis> AliasAccountGadis { get; set; }
        public virtual DbSet<AreeGadis> AreeGadis { get; set; }
        public virtual DbSet<Banche> Banche { get; set; }
        public virtual DbSet<Camere> Camere { get; set; }
        public virtual DbSet<Canali> Canali { get; set; }
        public virtual DbSet<CaratteristicheCamere> CaratteristicheCamere { get; set; }
        public virtual DbSet<CaratteristicheCliente> CaratteristicheCliente { get; set; }
        public virtual DbSet<CaratteristicheFornitore> CaratteristicheFornitore { get; set; }
        public virtual DbSet<CaratteristichePratica> CaratteristichePratica { get; set; }
        public virtual DbSet<CaratteristicheServizio> CaratteristicheServizio { get; set; }
        public virtual DbSet<CaratteristicheStruttura> CaratteristicheStruttura { get; set; }
        public virtual DbSet<Cataloghi> Cataloghi { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<CategorieMessaggi> CategorieMessaggi { get; set; }
        public virtual DbSet<CausaliAnnullamentoPratiche> CausaliAnnullamentoPratiche { get; set; }
        public virtual DbSet<CausaliLamentele> CausaliLamentele { get; set; }
        public virtual DbSet<Clienti> Clienti { get; set; }
        public virtual DbSet<ClientiAnno> ClientiAnno { get; set; }
        public virtual DbSet<ClientiAnnoSegmentiMarketing> ClientiAnnoSegmentiMarketing { get; set; }
        public virtual DbSet<ClientiArchivioNote> ClientiArchivioNote { get; set; }
        public virtual DbSet<ClientiCondizioniPagamento> ClientiCondizioniPagamento { get; set; }
        public virtual DbSet<ClientiTipiCamera> ClientiTipiCamera { get; set; }
        public virtual DbSet<CollezioniImmagini> CollezioniImmagini { get; set; }
        public virtual DbSet<ComuniAnagrafe> ComuniAnagrafe { get; set; }
        public virtual DbSet<ComuniCodiciPostali> ComuniCodiciPostali { get; set; }
        public virtual DbSet<CondizioniPagamento> CondizioniPagamento { get; set; }
        public virtual DbSet<CondizioniPagamentoCliente> CondizioniPagamentoCliente { get; set; }
        public virtual DbSet<Contatti> Contatti { get; set; }
        public virtual DbSet<ContattiCliente> ContattiCliente { get; set; }
        public virtual DbSet<ContattiFornitore> ContattiFornitore { get; set; }
        public virtual DbSet<DateAggiuntivePerSerie> DateAggiuntivePerSerie { get; set; }
        public virtual DbSet<Destinazioni> Destinazioni { get; set; }
        public virtual DbSet<DettagliFornitori> DettagliFornitori { get; set; }
        public virtual DbSet<DisponibilitaFornitore> DisponibilitaFornitore { get; set; }
        public virtual DbSet<Documenti> Documenti { get; set; }
        public virtual DbSet<ElementiOfferta> ElementiOfferta { get; set; }
        public virtual DbSet<ElementiOffertaTipiCamera> ElementiOffertaTipiCamera { get; set; }
        public virtual DbSet<ElementiOrdine> ElementiOrdine { get; set; }
        public virtual DbSet<ElementiOrdineTipiCamera> ElementiOrdineTipiCamera { get; set; }
        public virtual DbSet<ElenchiCommercialiServizi> ElenchiCommercialiServizi { get; set; }
        public virtual DbSet<Eventi> Eventi { get; set; }
        public virtual DbSet<FattureClienti> FattureClienti { get; set; }
        public virtual DbSet<FattureFornitori> FattureFornitori { get; set; }
        public virtual DbSet<FeedbackCliente> FeedbackCliente { get; set; }
        public virtual DbSet<FeedbackClienteServizi> FeedbackClienteServizi { get; set; }
        public virtual DbSet<Fornitori> Fornitori { get; set; }
        public virtual DbSet<FornitoriAnnoTariffe> FornitoriAnnoTariffe { get; set; }
        public virtual DbSet<FornitoriArchivioNote> FornitoriArchivioNote { get; set; }
        public virtual DbSet<FornitoriCondizioniPagamento> FornitoriCondizioniPagamento { get; set; }
        public virtual DbSet<FornitoriDettagli> FornitoriDettagli { get; set; }
        public virtual DbSet<FornitoriGuideAccompagnatori> FornitoriGuideAccompagnatori { get; set; }
        public virtual DbSet<FornitoriLocaliPubblici> FornitoriLocaliPubblici { get; set; }
        public virtual DbSet<FornitoriTrasportatori> FornitoriTrasportatori { get; set; }
        public virtual DbSet<FornitoriValutazioni> FornitoriValutazioni { get; set; }
        public virtual DbSet<Funzioni> Funzioni { get; set; }
        public virtual DbSet<FunzioniGO> FunzioniGO { get; set; }
        public virtual DbSet<GiornateOfferta> GiornateOfferta { get; set; }
        public virtual DbSet<GiornateOffertaPosiz> GiornateOffertaPosiz { get; set; }
        public virtual DbSet<GiornateOrdine> GiornateOrdine { get; set; }
        public virtual DbSet<GiornateOrdinePosiz> GiornateOrdinePosiz { get; set; }
        public virtual DbSet<Gratuita> Gratuita { get; set; }
        public virtual DbSet<GratuitaCondizioni> GratuitaCondizioni { get; set; }
        public virtual DbSet<Gruppi> Gruppi { get; set; }
        public virtual DbSet<Immagini> Immagini { get; set; }
        public virtual DbSet<Iva> Iva { get; set; }
        public virtual DbSet<IvaStorica> IvaStorica { get; set; }
        public virtual DbSet<Lamentele> Lamentele { get; set; }
        public virtual DbSet<Lingue> Lingue { get; set; }
        public virtual DbSet<LivelliDestinazione> LivelliDestinazione { get; set; }
        public virtual DbSet<LivelliUtente> LivelliUtente { get; set; }
        public virtual DbSet<Lock> Lock { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Manifestazioni> Manifestazioni { get; set; }
        public virtual DbSet<Messaggi> Messaggi { get; set; }
        public virtual DbSet<MessaggiDestinatari> MessaggiDestinatari { get; set; }
        public virtual DbSet<MessaggiEliminati> MessaggiEliminati { get; set; }
        public virtual DbSet<MessaggiEliminatiDestinatari> MessaggiEliminatiDestinatari { get; set; }
        public virtual DbSet<MezziPagamento> MezziPagamento { get; set; }
        public virtual DbSet<Moduli> Moduli { get; set; }
        public virtual DbSet<Nazioni> Nazioni { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<Offerte> Offerte { get; set; }
        public virtual DbSet<OffertePubbliche> OffertePubbliche { get; set; }
        public virtual DbSet<OfferteTotali> OfferteTotali { get; set; }
        public virtual DbSet<OfferteTotaliSezioni> OfferteTotaliSezioni { get; set; }
        public virtual DbSet<Operatori> Operatori { get; set; }
        public virtual DbSet<OperatoriAccountEmail> OperatoriAccountEmail { get; set; }
        public virtual DbSet<OperatoriFunzioni> OperatoriFunzioni { get; set; }
        public virtual DbSet<Opportunita> Opportunita { get; set; }
        public virtual DbSet<OrdiniTotali> OrdiniTotali { get; set; }
        public virtual DbSet<OrdiniTotaliSezioni> OrdiniTotaliSezioni { get; set; }
        public virtual DbSet<OriginiClienti> OriginiClienti { get; set; }
        public virtual DbSet<PagamentiRicevuti> PagamentiRicevuti { get; set; }
        public virtual DbSet<PagamentiRicevutiRighe> PagamentiRicevutiRighe { get; set; }
        public virtual DbSet<Parametri> Parametri { get; set; }
        public virtual DbSet<Partecipanti> Partecipanti { get; set; }
        public virtual DbSet<Pratiche> Pratiche { get; set; }
        public virtual DbSet<PratichePagamentiCliente> PratichePagamentiCliente { get; set; }
        public virtual DbSet<PratichePagamentiFornitori> PratichePagamentiFornitori { get; set; }
        public virtual DbSet<PraticheSistemazioni> PraticheSistemazioni { get; set; }
        public virtual DbSet<PraticheSistemazioniTipiCamera> PraticheSistemazioniTipiCamera { get; set; }
        public virtual DbSet<PraticheTag> PraticheTag { get; set; }
        public virtual DbSet<ProprietaStili> ProprietaStili { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<PuntiDestinazione> PuntiDestinazione { get; set; }
        public virtual DbSet<Regioni> Regioni { get; set; }
        public virtual DbSet<RichDisp> RichDisp { get; set; }
        public virtual DbSet<RichForn> RichForn { get; set; }
        public virtual DbSet<RichFornServizi> RichFornServizi { get; set; }
        public virtual DbSet<RiferimentiFornitore> RiferimentiFornitore { get; set; }
        public virtual DbSet<S_Aree> S_Aree { get; set; }
        public virtual DbSet<S_AreeSegmentiMarketing> S_AreeSegmentiMarketing { get; set; }
        public virtual DbSet<S_AreeTipiServizio> S_AreeTipiServizio { get; set; }
        public virtual DbSet<S_Clienti> S_Clienti { get; set; }
        public virtual DbSet<S_ClientiSegmentiMarketing> S_ClientiSegmentiMarketing { get; set; }
        public virtual DbSet<S_ClientiTipiServizio> S_ClientiTipiServizio { get; set; }
        public virtual DbSet<S_Destinazioni> S_Destinazioni { get; set; }
        public virtual DbSet<S_Fornitori> S_Fornitori { get; set; }
        public virtual DbSet<S_FornitoriTipiServizio> S_FornitoriTipiServizio { get; set; }
        public virtual DbSet<S_SegmentiMarketing> S_SegmentiMarketing { get; set; }
        public virtual DbSet<S_TipiServizio> S_TipiServizio { get; set; }
        public virtual DbSet<Scadenze> Scadenze { get; set; }
        public virtual DbSet<ScaglioniSezioneOfferta> ScaglioniSezioneOfferta { get; set; }
        public virtual DbSet<ScaglioniSezioneOrdine> ScaglioniSezioneOrdine { get; set; }
        public virtual DbSet<SediGadis> SediGadis { get; set; }
        public virtual DbSet<SegmentiMarketing> SegmentiMarketing { get; set; }
        public virtual DbSet<Servizi> Servizi { get; set; }
        public virtual DbSet<Servizi_TEMP> Servizi_TEMP { get; set; }
        public virtual DbSet<Servizi2> Servizi2 { get; set; }
        public virtual DbSet<ServiziFornitoriAnno> ServiziFornitoriAnno { get; set; }
        public virtual DbSet<SezioniCatalogo> SezioniCatalogo { get; set; }
        public virtual DbSet<SezioniOfferta> SezioniOfferta { get; set; }
        public virtual DbSet<SezioniOrdine> SezioniOrdine { get; set; }
        public virtual DbSet<StatiElementoOrdine> StatiElementoOrdine { get; set; }
        public virtual DbSet<StatiPratica> StatiPratica { get; set; }
        public virtual DbSet<Stili> Stili { get; set; }
        public virtual DbSet<Stringhe> Stringhe { get; set; }
        public virtual DbSet<StringheLingue> StringheLingue { get; set; }
        public virtual DbSet<TagPratiche> TagPratiche { get; set; }
        public virtual DbSet<TagPratichePratica> TagPratichePratica { get; set; }
        public virtual DbSet<TasseSoggiorno> TasseSoggiorno { get; set; }
        public virtual DbSet<TasseSoggiornoRighe> TasseSoggiornoRighe { get; set; }
        public virtual DbSet<TipiAttivita> TipiAttivita { get; set; }
        public virtual DbSet<TipiCamera> TipiCamera { get; set; }
        public virtual DbSet<TipiDocumento> TipiDocumento { get; set; }
        public virtual DbSet<TipiDocumentoModelli> TipiDocumentoModelli { get; set; }
        public virtual DbSet<TipiFornitore> TipiFornitore { get; set; }
        public virtual DbSet<TipiScadenza> TipiScadenza { get; set; }
        public virtual DbSet<TipiServizio> TipiServizio { get; set; }
        public virtual DbSet<TipoRichForn> TipoRichForn { get; set; }
        public virtual DbSet<UsiDocumento> UsiDocumento { get; set; }
        public virtual DbSet<UsiImmagine> UsiImmagine { get; set; }
        public virtual DbSet<UsiStringa> UsiStringa { get; set; }
        public virtual DbSet<Valute> Valute { get; set; }
        public virtual DbSet<VariantiLogisticheServizio> VariantiLogisticheServizio { get; set; }
        public virtual DbSet<VariantiPrezziFornitoriAnnoTariffe> VariantiPrezziFornitoriAnnoTariffe { get; set; }
        public virtual DbSet<VariantiPrezziServizioFornitoreAnno> VariantiPrezziServizioFornitoreAnno { get; set; }
        public virtual DbSet<VersioniSoftware> VersioniSoftware { get; set; }
        public virtual DbSet<AreeAnno> AreeAnno { get; set; }
        public virtual DbSet<AreeAnnoSegmentiMarketing> AreeAnnoSegmentiMarketing { get; set; }
        public virtual DbSet<DestinazioniImport> DestinazioniImport { get; set; }
        public virtual DbSet<Z_Sincro_attivita_relazioni> Z_Sincro_attivita_relazioni { get; set; }
        public virtual DbSet<Z_Sincro_attivita_segmenti> Z_Sincro_attivita_segmenti { get; set; }
        public virtual DbSet<Z_Sincro_Dizionario_Servizi_Fornitori_Passo2> Z_Sincro_Dizionario_Servizi_Fornitori_Passo2 { get; set; }
        public virtual DbSet<Z_Sincro_Dizionario_Servizi_NoName_Passo2> Z_Sincro_Dizionario_Servizi_NoName_Passo2 { get; set; }
        public virtual DbSet<Z_Sincro_GO4_Fornitori_SchedePrezzi_Fornitori_Passo2> Z_Sincro_GO4_Fornitori_SchedePrezzi_Fornitori_Passo2 { get; set; }
        public virtual DbSet<Z_Sincro_GO4_Fornitori_SchedePrezzi_Passo2> Z_Sincro_GO4_Fornitori_SchedePrezzi_Passo2 { get; set; }
        public virtual DbSet<Z_Sincro_GO4_Fornitori_SchedePrezzi_VariantiPrezzi_DaInserire> Z_Sincro_GO4_Fornitori_SchedePrezzi_VariantiPrezzi_DaInserire { get; set; }
        public virtual DbSet<Z_Sincro_GO4_Fornitori_SchedePrezzi_VariantiPrezzi_Nuovi> Z_Sincro_GO4_Fornitori_SchedePrezzi_VariantiPrezzi_Nuovi { get; set; }
        public virtual DbSet<Z_Sincro_GO4_Fornitori_SchedePrezziLingue_Aggiornati_Dizionario_Base> Z_Sincro_GO4_Fornitori_SchedePrezziLingue_Aggiornati_Dizionario_Base { get; set; }
        public virtual DbSet<Z_Sincro_Pratiche_DocumentiCreati> Z_Sincro_Pratiche_DocumentiCreati { get; set; }
        public virtual DbSet<Z_Sincro_Pratiche_DocumentiRicevuti> Z_Sincro_Pratiche_DocumentiRicevuti { get; set; }
        public virtual DbSet<Z_Sincro_Pratiche_ElementiOfferta_DaAggiungere> Z_Sincro_Pratiche_ElementiOfferta_DaAggiungere { get; set; }
        public virtual DbSet<Z_Sincro_Pratiche_ElementiOrdini_DaAggiungere> Z_Sincro_Pratiche_ElementiOrdini_DaAggiungere { get; set; }
        public virtual DbSet<Z_Sincro_Pratiche_OfferteSezioni> Z_Sincro_Pratiche_OfferteSezioni { get; set; }
        public virtual DbSet<Z_Sincro_Pratiche_Servizi_Connessione> Z_Sincro_Pratiche_Servizi_Connessione { get; set; }
        public virtual DbSet<Z_Sincro_Pratiche_Servizi_Dettaglio> Z_Sincro_Pratiche_Servizi_Dettaglio { get; set; }
    }
}
