//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiornateOfferta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiornateOfferta()
        {
            this.GiornateOffertaPosiz = new HashSet<GiornateOffertaPosiz>();
        }
    
        public int AnnoPratica { get; set; }
        public int NumPratica { get; set; }
        public short NumOfferta { get; set; }
        public short NumGiornata { get; set; }
        public string Descrizione { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Offerte Offerte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiornateOffertaPosiz> GiornateOffertaPosiz { get; set; }
    }
}
