//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiornateOffertaPosiz
    {
        public int AnnoPratica { get; set; }
        public int NumPratica { get; set; }
        public short NumOfferta { get; set; }
        public short NumGiornata { get; set; }
        public short NumPosiz { get; set; }
        public Nullable<short> NumSezione { get; set; }
        public Nullable<short> ElementoOffertaID { get; set; }
        public string Testo { get; set; }
        public bool FlagVisibileInDocOfferta { get; set; }
    
        public virtual ElementiOfferta ElementiOfferta { get; set; }
        public virtual GiornateOfferta GiornateOfferta { get; set; }
    }
}
