//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GratuitaCondizioni
    {
        public string GratuitaID { get; set; }
        public short NumProgCondizione { get; set; }
        public Nullable<short> CondizioneGratuita { get; set; }
        public Nullable<short> FattoreGratuita { get; set; }
        public Nullable<short> LimiteGratuita { get; set; }
        public string PerGratuita { get; set; }
        public Nullable<short> Sistemazione { get; set; }
        public Nullable<short> Collegamento { get; set; }
        public Nullable<short> NumGratuita { get; set; }
    
        public virtual Gratuita Gratuita { get; set; }
    }
}
