//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lamentele
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lamentele()
        {
            this.Scadenze = new HashSet<Scadenze>();
        }
    
        public long LamentelaID { get; set; }
        public Nullable<short> Causale { get; set; }
        public string Testo { get; set; }
        public string Operatore { get; set; }
        public string Stato { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public string OperatoreChiusura { get; set; }
        public Nullable<System.DateTime> DataChiusura { get; set; }
        public Nullable<int> DestinazioneID { get; set; }
        public string EsitoFinale { get; set; }
        public string EsitoVerifica { get; set; }
        public Nullable<int> FornitoreID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<int> AnnoPratica { get; set; }
        public Nullable<int> NumPratica { get; set; }
        public Nullable<int> ServizioID { get; set; }
    
        public virtual CausaliLamentele CausaliLamentele { get; set; }
        public virtual Clienti Clienti { get; set; }
        public virtual Destinazioni Destinazioni { get; set; }
        public virtual Fornitori Fornitori { get; set; }
        public virtual Operatori Operatori { get; set; }
        public virtual Operatori Operatori1 { get; set; }
        public virtual Pratiche Pratiche { get; set; }
        public virtual Servizi Servizi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scadenze> Scadenze { get; set; }
    }
}
