//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Thread { get; set; }
        public string Level { get; set; }
        public string Logger { get; set; }
        public string Messaggio { get; set; }
        public string Exception { get; set; }
        public string HostName { get; set; }
        public string IdSessione { get; set; }
        public string OperatoreID { get; set; }
        public string IdUtenteDominio { get; set; }
        public string SiglaFunzione { get; set; }
        public bool isAbilitato { get; set; }
    
        public virtual Funzioni Funzioni { get; set; }
        public virtual Operatori Operatori { get; set; }
    }
}
