//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessaggiEliminati
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MessaggiEliminati()
        {
            this.MessaggiEliminatiDestinatari = new HashSet<MessaggiEliminatiDestinatari>();
        }
    
        public long MessaggioID { get; set; }
        public string Oggetto { get; set; }
        public string Testo { get; set; }
        public Nullable<System.DateTime> DataOraInvio { get; set; }
        public System.DateTime DataOraSalvataggio { get; set; }
        public string CanaleID { get; set; }
        public Nullable<short> CategoriaMsgID { get; set; }
        public string Mittente { get; set; }
        public string DescrizioneMittente { get; set; }
        public string OperatoreID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> FornitoreID { get; set; }
        public Nullable<int> NumPratica { get; set; }
        public Nullable<int> AnnoPratica { get; set; }
        public bool IsMsgEntrata { get; set; }
        public string NoteInterne { get; set; }
        public Nullable<System.DateTime> DataPrimaLettura { get; set; }
        public string OperatorePrimaLetturaID { get; set; }
        public Nullable<System.DateTime> DataArchiviazione { get; set; }
        public string OperatoreArchiviazioneID { get; set; }
        public bool FlagCompletato { get; set; }
        public Nullable<short> DimensioneK { get; set; }
        public System.DateTime DataEliminazione { get; set; }
        public string OperatoreEliminazioneID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessaggiEliminatiDestinatari> MessaggiEliminatiDestinatari { get; set; }
    }
}
