//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messaggi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Messaggi()
        {
            this.MessaggiDestinatari = new HashSet<MessaggiDestinatari>();
            this.PraticheSistemazioni = new HashSet<PraticheSistemazioni>();
            this.RichDisp = new HashSet<RichDisp>();
            this.RichForn = new HashSet<RichForn>();
            this.RichForn1 = new HashSet<RichForn>();
            this.Documenti = new HashSet<Documenti>();
        }
    
        public long MessaggioID { get; set; }
        public string Oggetto { get; set; }
        public string Testo { get; set; }
        public Nullable<System.DateTime> DataOraInvio { get; set; }
        public System.DateTime DataOraSalvataggio { get; set; }
        public string CanaleID { get; set; }
        public Nullable<short> CategoriaMsgID { get; set; }
        public string Mittente { get; set; }
        public string OperatoreID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> FornitoreID { get; set; }
        public Nullable<int> NumPratica { get; set; }
        public Nullable<int> AnnoPratica { get; set; }
        public bool IsMsgEntrata { get; set; }
        public string NoteInterne { get; set; }
        public Nullable<System.DateTime> DataLettura { get; set; }
        public string OperatoreLetturaID { get; set; }
        public Nullable<System.DateTime> DataArchiviazione { get; set; }
        public string OperatoreArchiviazioneID { get; set; }
        public string MailID { get; set; }
        public Nullable<short> DimensioneK { get; set; }
        public bool FlagCompletato { get; set; }
        public bool FlagSpam { get; set; }
        public string DescrizioneMittente { get; set; }
        public string TestoMailServizio { get; set; }
        public Nullable<long> OldId { get; set; }
    
        public virtual CategorieMessaggi CategorieMessaggi { get; set; }
        public virtual Clienti Clienti { get; set; }
        public virtual Fornitori Fornitori { get; set; }
        public virtual Pratiche Pratiche { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessaggiDestinatari> MessaggiDestinatari { get; set; }
        public virtual Operatori Operatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PraticheSistemazioni> PraticheSistemazioni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RichDisp> RichDisp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RichForn> RichForn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RichForn> RichForn1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documenti> Documenti { get; set; }
    }
}
