//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessaggiDestinatari
    {
        public long MessaggioID { get; set; }
        public short DestID { get; set; }
        public string TipoInvio { get; set; }
        public string Destinatario { get; set; }
        public string DescrizioneDestinatario { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> FornitoreID { get; set; }
        public string AliasDestinatario { get; set; }
    
        public virtual Clienti Clienti { get; set; }
        public virtual Fornitori Fornitori { get; set; }
        public virtual Messaggi Messaggi { get; set; }
    }
}
