//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffertePubbliche
    {
        public int OffertaPubblicaID { get; set; }
        public string AnnoPratica { get; set; }
        public Nullable<int> NumPratica { get; set; }
        public Nullable<short> AreaGadisID { get; set; }
        public Nullable<int> DestinazioneID { get; set; }
        public Nullable<double> CostoAPax { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<short> NewsletterID { get; set; }
        public Nullable<int> PostSuCanaleID { get; set; }
        public Nullable<short> CatalogoID { get; set; }
        public Nullable<short> SezioneCatalogoID { get; set; }
        public Nullable<int> FornitoreID { get; set; }
        public Nullable<int> ServizioID { get; set; }
    
        public virtual AreeGadis AreeGadis { get; set; }
        public virtual Servizi Servizi { get; set; }
    }
}
