//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offerte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offerte()
        {
            this.Documenti = new HashSet<Documenti>();
            this.GiornateOfferta = new HashSet<GiornateOfferta>();
            this.OfferteTotali = new HashSet<OfferteTotali>();
            this.SezioniOfferta = new HashSet<SezioniOfferta>();
            this.SezioniOrdine = new HashSet<SezioniOrdine>();
            this.UsiDocumento = new HashSet<UsiDocumento>();
        }
    
        public int AnnoPratica { get; set; }
        public int NumPratica { get; set; }
        public short NumOfferta { get; set; }
        public Nullable<System.DateTime> DataInvioOfferta { get; set; }
        public Nullable<System.DateTime> DataScadenzaOpzione { get; set; }
        public Nullable<System.DateTime> DataConfermaCliente1liv { get; set; }
        public Nullable<double> MargineTarget { get; set; }
        public Nullable<short> NumMinPax { get; set; }
        public string Titolo { get; set; }
        public string DescrizioneCommerciale { get; set; }
        public string DescrizioneDay_by_day { get; set; }
        public string DescrizioneServiziInclusi { get; set; }
        public Nullable<double> PrezzoVenditaSeCatalogo { get; set; }
        public Nullable<System.DateTime> DataScadenzaInvioOfferta { get; set; }
        public Nullable<short> NumPaxCalcolo { get; set; }
        public Nullable<short> NumPaxSingoleCalcolo { get; set; }
        public Nullable<short> NumGratuitaCalcolo { get; set; }
        public Nullable<short> NumGratuitaSingoleCalcolo { get; set; }
        public short ProgOfferta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documenti> Documenti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiornateOfferta> GiornateOfferta { get; set; }
        public virtual Pratiche Pratiche { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferteTotali> OfferteTotali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SezioniOfferta> SezioniOfferta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SezioniOrdine> SezioniOrdine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsiDocumento> UsiDocumento { get; set; }
    }
}
