//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatoriFunzioni
    {
        public string OperatoreID { get; set; }
        public string SiglaFunzione { get; set; }
        public byte LivelloAbilitazione { get; set; }
    
        public virtual Funzioni Funzioni { get; set; }
        public virtual Operatori Operatori { get; set; }
    }
}
