//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatoriAccountEmail
    {
        public int AccountEmailGadisID { get; set; }
        public string OperatoreID { get; set; }
        public bool isAbilitato { get; set; }
        public Nullable<bool> isDefault { get; set; }
    
        public virtual AccountEmailGadis AccountEmailGadis { get; set; }
        public virtual Operatori Operatori { get; set; }
    }
}
