//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opportunita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opportunita()
        {
            this.Pratiche = new HashSet<Pratiche>();
            this.Scadenze = new HashSet<Scadenze>();
            this.SegmentiMarketing = new HashSet<SegmentiMarketing>();
        }
    
        public int OpportunitaID { get; set; }
        public Nullable<int> DestinazioneID { get; set; }
        public short AreaGadisID { get; set; }
        public Nullable<short> NumeroPax { get; set; }
        public string Periodo { get; set; }
        public string Note { get; set; }
        public Nullable<int> ContattoID { get; set; }
        public Nullable<int> AnnoOpportunita { get; set; }
        public string OperatoreID { get; set; }
        public Nullable<System.DateTime> DataRegistrazione { get; set; }
        public Nullable<System.DateTime> DataScadenzaOpportunita { get; set; }
        public Nullable<short> ImportanzaBusiness { get; set; }
        public bool FlagPraticheGenerate { get; set; }
        public Nullable<short> Mese { get; set; }
    
        public virtual AreeGadis AreeGadis { get; set; }
        public virtual Contatti Contatti { get; set; }
        public virtual Destinazioni Destinazioni { get; set; }
        public virtual Operatori Operatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pratiche> Pratiche { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scadenze> Scadenze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentiMarketing> SegmentiMarketing { get; set; }
    }
}
