//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdiniTotali
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdiniTotali()
        {
            this.OrdiniTotaliSezioni = new HashSet<OrdiniTotaliSezioni>();
        }
    
        public int AnnoPratica { get; set; }
        public int NumPratica { get; set; }
        public short NumTotale { get; set; }
        public string NomeTotale { get; set; }
        public string SiglaTotale { get; set; }
    
        public virtual Pratiche Pratiche { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdiniTotaliSezioni> OrdiniTotaliSezioni { get; set; }
    }
}
