//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagamentiRicevutiRighe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PagamentiRicevutiRighe()
        {
            this.PratichePagamentiCliente = new HashSet<PratichePagamentiCliente>();
        }
    
        public int PagamentoID { get; set; }
        public short RigaID { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
        public string Banca { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public double Importo { get; set; }
        public string TestoCausalePagamento { get; set; }
        public bool FlagAssociatoPratiche { get; set; }
        public string Note { get; set; }
        public string Pagante { get; set; }
        public string PraticheRiconosciute { get; set; }
    
        public virtual Banche Banche { get; set; }
        public virtual Clienti Clienti { get; set; }
        public virtual PagamentiRicevuti PagamentiRicevuti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PratichePagamentiCliente> PratichePagamentiCliente { get; set; }
    }
}
