//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametri
    {
        public short ConfigurazioneID { get; set; }
        public bool LastVersion { get; set; }
        public System.DateTime DataVersione { get; set; }
        public string OperatoreAggiornamento { get; set; }
        public Nullable<short> DurataMaxPratiche { get; set; }
        public Nullable<short> NumGiorniScadenzaReleaseCliente { get; set; }
        public Nullable<short> NumGiorniScadenzaReleaseFornitore { get; set; }
        public Nullable<short> NumGiorniScadenzaOpzioneFornitore { get; set; }
        public Nullable<short> NumGiorniInvioOfferta { get; set; }
        public Nullable<short> NumGiorniScadenzaOpzioneCliente { get; set; }
        public Nullable<short> NumGiorniScadPreArrivoGruppo { get; set; }
        public Nullable<short> NumGiorniScadPostArrivoGruppo { get; set; }
        public Nullable<short> NumGiorniProgrammaPreArrivoGruppo { get; set; }
        public Nullable<short> NumGiorniVoucherPreArrivoGruppo { get; set; }
        public Nullable<short> IvaAttuale { get; set; }
        public string GlobalEmailFooterIT { get; set; }
        public string GlobalEmailFooterDE { get; set; }
        public string GlobalEmailFooterEN { get; set; }
        public string GlobalEmailFooterFR { get; set; }
        public Nullable<short> TipoAttivitaStdClienteID { get; set; }
        public Nullable<short> SegmentoMarketingStdID { get; set; }
        public string CodTipoCamera1StdID { get; set; }
        public string CodTipoCamera2StdID { get; set; }
        public string GratuitaStdClienteID { get; set; }
        public string GratuitaStdFornitoreID { get; set; }
        public Nullable<short> AccontoClienteStdID { get; set; }
        public Nullable<short> SaldoClienteStdID { get; set; }
        public Nullable<short> AccontoFornitoreStdID { get; set; }
        public Nullable<short> SaldoFornitoreStdID { get; set; }
        public Nullable<double> MargineTarget { get; set; }
        public string EmailNotifiche { get; set; }
        public string PercorsoMail { get; set; }
        public string DestinatariReport { get; set; }
        public Nullable<short> NumMinPaxPratica { get; set; }
        public Nullable<short> NumMaxPaxPratica { get; set; }
        public Nullable<short> NumGiorniSollecitoOfferta { get; set; }
    
        public virtual Operatori Operatori { get; set; }
    }
}
