//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PraticheSistemazioni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PraticheSistemazioni()
        {
            this.PraticheSistemazioniTipiCamera = new HashSet<PraticheSistemazioniTipiCamera>();
        }
    
        public int AnnoPratica { get; set; }
        public int NumPratica { get; set; }
        public System.DateTime DataAgg { get; set; }
        public string Note { get; set; }
        public short StatoPratica { get; set; }
        public Nullable<long> MessaggioID { get; set; }
    
        public virtual Messaggi Messaggi { get; set; }
        public virtual Pratiche Pratiche { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PraticheSistemazioniTipiCamera> PraticheSistemazioniTipiCamera { get; set; }
        public virtual StatiPratica StatiPratica { get; set; }
    }
}
