//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pratiche
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pratiche()
        {
            this.DateAggiuntivePerSerie = new HashSet<DateAggiuntivePerSerie>();
            this.Documenti = new HashSet<Documenti>();
            this.FattureClienti = new HashSet<FattureClienti>();
            this.FattureFornitori = new HashSet<FattureFornitori>();
            this.Fornitori = new HashSet<Fornitori>();
            this.GiornateOrdine = new HashSet<GiornateOrdine>();
            this.Lamentele = new HashSet<Lamentele>();
            this.Messaggi = new HashSet<Messaggi>();
            this.Note = new HashSet<Note>();
            this.Offerte = new HashSet<Offerte>();
            this.OrdiniTotali = new HashSet<OrdiniTotali>();
            this.PraticheSistemazioni = new HashSet<PraticheSistemazioni>();
            this.Pratiche1 = new HashSet<Pratiche>();
            this.PratichePagamentiCliente = new HashSet<PratichePagamentiCliente>();
            this.PratichePagamentiFornitori = new HashSet<PratichePagamentiFornitori>();
            this.PraticheTag = new HashSet<PraticheTag>();
            this.RichDisp = new HashSet<RichDisp>();
            this.RichForn = new HashSet<RichForn>();
            this.Scadenze = new HashSet<Scadenze>();
            this.SezioniOrdine = new HashSet<SezioniOrdine>();
            this.UsiDocumento = new HashSet<UsiDocumento>();
            this.SegmentiMarketing = new HashSet<SegmentiMarketing>();
        }
    
        public int AnnoPratica { get; set; }
        public int NumPratica { get; set; }
        public System.DateTime Dal { get; set; }
        public System.DateTime Al { get; set; }
        public Nullable<short> StatoId { get; set; }
        public Nullable<System.DateTime> DataInvioProgramma { get; set; }
        public Nullable<System.DateTime> DataInvioVoucher { get; set; }
        public Nullable<System.DateTime> DataInvioRoomingList { get; set; }
        public System.DateTime DataCreazionePratica { get; set; }
        public Nullable<System.DateTime> DataRichiesta { get; set; }
        public Nullable<System.DateTime> DataReleaseCliente { get; set; }
        public Nullable<System.DateTime> DataInvio1Offerta { get; set; }
        public Nullable<System.DateTime> DataConfermaCliente1Liv { get; set; }
        public Nullable<System.DateTime> DataNostraConferma { get; set; }
        public Nullable<System.DateTime> DataConfermaDefinitiva { get; set; }
        public Nullable<System.DateTime> DataAnnullamento { get; set; }
        public Nullable<short> CodCausaleAnnullamento { get; set; }
        public Nullable<short> DurataInGg { get; set; }
        public Nullable<short> NumMinPax { get; set; }
        public Nullable<short> NumMaxPax { get; set; }
        public Nullable<short> NumPax { get; set; }
        public Nullable<short> NumPaxSingole { get; set; }
        public Nullable<short> NumGratuita { get; set; }
        public Nullable<short> NumGratuitaSingole { get; set; }
        public string GratuitaID { get; set; }
        public string RiferimentoPraticaCliente { get; set; }
        public bool IsPraticaGenerica { get; set; }
        public string ResponsabilePraticaCliente { get; set; }
        public string InfoViaggio { get; set; }
        public Nullable<double> PercCommissioneIntermediario { get; set; }
        public Nullable<double> ValoreCambio { get; set; }
        public Nullable<System.DateTime> DataCambio { get; set; }
        public string AnnoContabileGadis { get; set; }
        public string Codcondizionerelease { get; set; }
        public string DestinazioneStatistica { get; set; }
        public string CaratteristicheViaggioID { get; set; }
        public int ClienteID { get; set; }
        public Nullable<int> ClienteFatturazioneID { get; set; }
        public Nullable<int> ClienteIntermediarioID { get; set; }
        public Nullable<int> DestinazioneID { get; set; }
        public Nullable<int> FatturaPraticaClienteID { get; set; }
        public string OperatoreID { get; set; }
        public Nullable<short> AreaGadisID { get; set; }
        public Nullable<short> CodiceValuta { get; set; }
        public bool IsFatturabile { get; set; }
        public Nullable<short> IdLinguaPratica { get; set; }
        public string NoteRichiestaCliente { get; set; }
        public short NumVersione { get; set; }
        public System.DateTime DataUltAgg { get; set; }
        public string NoteInterne { get; set; }
        public bool HaLamentele { get; set; }
        public Nullable<short> ContattoRespPraticaClienteID { get; set; }
        public Nullable<short> ContattoCapogruppoID { get; set; }
        public string CapogruppoNonCliente { get; set; }
        public Nullable<short> ContattoAutistaID { get; set; }
        public string AutistaNonCliente { get; set; }
        public bool FlagOrdineModificato { get; set; }
        public Nullable<short> FeedbackOperatore { get; set; }
        public Nullable<System.DateTime> DataFeedbackOperatore { get; set; }
        public string OperatoreAutoreFeedback { get; set; }
        public Nullable<short> StatoPreAnnullamento { get; set; }
        public string OperUltAgg { get; set; }
        public Nullable<int> OpportunitaID { get; set; }
        public Nullable<int> AnnoPraticaMadre { get; set; }
        public Nullable<int> NumPraticaMadre { get; set; }
        public bool FlagTour { get; set; }
        public bool FlagExpress { get; set; }
        public Nullable<System.DateTime> DataRichAnnullamento { get; set; }
        public Nullable<short> NumGiorniScadenzaRelease { get; set; }
        public string OperatoreIDPrecedente { get; set; }
        public Nullable<System.DateTime> DataCambioOperatore { get; set; }
        public Nullable<double> TotaleCosti { get; set; }
        public Nullable<double> TotaleRicavi { get; set; }
        public Nullable<double> MargineTotale { get; set; }
        public Nullable<System.DateTime> DataExportSuAdHoc { get; set; }
        public bool FlagPraticaDaPregresso { get; set; }
    
        public virtual AreeGadis AreeGadis { get; set; }
        public virtual CaratteristichePratica CaratteristichePratica { get; set; }
        public virtual CausaliAnnullamentoPratiche CausaliAnnullamentoPratiche { get; set; }
        public virtual Clienti Clienti { get; set; }
        public virtual Clienti Clienti1 { get; set; }
        public virtual Clienti Clienti2 { get; set; }
        public virtual ContattiCliente ContattiCliente { get; set; }
        public virtual ContattiCliente ContattiCliente1 { get; set; }
        public virtual ContattiCliente ContattiCliente2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DateAggiuntivePerSerie> DateAggiuntivePerSerie { get; set; }
        public virtual Destinazioni Destinazioni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documenti> Documenti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FattureClienti> FattureClienti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FattureFornitori> FattureFornitori { get; set; }
        public virtual FeedbackCliente FeedbackCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fornitori> Fornitori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiornateOrdine> GiornateOrdine { get; set; }
        public virtual Gratuita Gratuita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lamentele> Lamentele { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Messaggi> Messaggi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Note { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offerte> Offerte { get; set; }
        public virtual Operatori Operatori { get; set; }
        public virtual Operatori Operatori1 { get; set; }
        public virtual Operatori Operatori2 { get; set; }
        public virtual Opportunita Opportunita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdiniTotali> OrdiniTotali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PraticheSistemazioni> PraticheSistemazioni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pratiche> Pratiche1 { get; set; }
        public virtual Pratiche Pratiche2 { get; set; }
        public virtual StatiPratica StatiPratica { get; set; }
        public virtual StatiPratica StatiPratica1 { get; set; }
        public virtual Valute Valute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PratichePagamentiCliente> PratichePagamentiCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PratichePagamentiFornitori> PratichePagamentiFornitori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PraticheTag> PraticheTag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RichDisp> RichDisp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RichForn> RichForn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scadenze> Scadenze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SezioniOrdine> SezioniOrdine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsiDocumento> UsiDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentiMarketing> SegmentiMarketing { get; set; }
    }
}
