//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProprietaStili
    {
        public short IdStile { get; set; }
        public string NomeProprieta { get; set; }
        public string ValoreProprieta { get; set; }
    
        public virtual Stili Stili { get; set; }
    }
}
