//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntiDestinazione
    {
        public int DestinazioneID { get; set; }
        public short ProgPunto { get; set; }
        public decimal Latitudine { get; set; }
        public decimal Longitudine { get; set; }
    
        public virtual Destinazioni Destinazioni { get; set; }
    }
}
