//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RichFornServizi
    {
        public int AnnoPratica { get; set; }
        public int NumPratica { get; set; }
        public short ProgPratica { get; set; }
        public int ServizioID { get; set; }
        public int FornitoreID { get; set; }
    
        public virtual RichForn RichForn { get; set; }
    }
}
