//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_FornitoriTipiServizio
    {
        public int FornitoreID { get; set; }
        public int AnnoRilevazione { get; set; }
        public short MeseRilevazione { get; set; }
        public int AnnoPratiche { get; set; }
        public int TipoServizioID { get; set; }
        public Nullable<double> CostiServiziFatturati { get; set; }
        public Nullable<short> PraticheFatturate { get; set; }
        public Nullable<short> NumServiziEffettuati { get; set; }
        public Nullable<double> PercSuNumTotalePraticheFatturate { get; set; }
    }
}
