//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scadenze
    {
        public int AnnoScadenza { get; set; }
        public int ScadenzaID { get; set; }
        public System.DateTime Data { get; set; }
        public short CodTipoScadenza { get; set; }
        public string Testo { get; set; }
        public string OperatoreID { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> AnnoPratica { get; set; }
        public Nullable<int> Pratica { get; set; }
        public Nullable<short> NumOfferta { get; set; }
        public Nullable<System.DateTime> DataSpunta { get; set; }
        public Nullable<int> Fornitore { get; set; }
        public bool IsAutomatica { get; set; }
        public Nullable<short> PraticaPagamentoPrevistoFornitoreID { get; set; }
        public Nullable<short> PraticaPagamentoPrevistoClienteID { get; set; }
        public Nullable<short> NumSezioneOfferta { get; set; }
        public Nullable<short> ElementoOffertaID { get; set; }
        public Nullable<short> NumSezioneOrdine { get; set; }
        public Nullable<short> ElementoOrdineID { get; set; }
        public Nullable<long> LamentelaID { get; set; }
        public Nullable<int> OpportunitaID { get; set; }
        public bool FlagPrioritaria { get; set; }
    
        public virtual Clienti Clienti { get; set; }
        public virtual ElementiOfferta ElementiOfferta { get; set; }
        public virtual ElementiOrdine ElementiOrdine { get; set; }
        public virtual Fornitori Fornitori { get; set; }
        public virtual Lamentele Lamentele { get; set; }
        public virtual Operatori Operatori { get; set; }
        public virtual Opportunita Opportunita { get; set; }
        public virtual Pratiche Pratiche { get; set; }
        public virtual PratichePagamentiCliente PratichePagamentiCliente { get; set; }
        public virtual PratichePagamentiFornitori PratichePagamentiFornitori { get; set; }
        public virtual TipiScadenza TipiScadenza { get; set; }
    }
}
