//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScaglioniSezioneOrdine
    {
        public int AnnoPratica { get; set; }
        public int NumPratica { get; set; }
        public short NumSezione { get; set; }
        public short NumScaglione { get; set; }
        public Nullable<short> SogliaMinPax { get; set; }
        public Nullable<short> SogliaMaxPax { get; set; }
        public Nullable<double> PrezzoVendita { get; set; }
        public Nullable<double> PrezzoVenditaInValuta { get; set; }
        public Nullable<double> Margine { get; set; }
        public Nullable<short> FreeVendita { get; set; }
        public Nullable<short> NumSingole { get; set; }
        public Nullable<short> NumGratuitaSingole { get; set; }
        public Nullable<double> PrezzoVenditaSingole { get; set; }
    
        public virtual SezioniOrdine SezioniOrdine { get; set; }
    }
}
