//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentiMarketing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SegmentiMarketing()
        {
            this.Clienti = new HashSet<Clienti>();
            this.Fornitori = new HashSet<Fornitori>();
            this.Opportunita = new HashSet<Opportunita>();
            this.Pratiche = new HashSet<Pratiche>();
            this.Servizi = new HashSet<Servizi>();
        }
    
        public short SegmentoMarketingID { get; set; }
        public string NoteInterne { get; set; }
        public string Nome { get; set; }
        public string NomeLungo { get; set; }
        public Nullable<int> Prog { get; set; }
        public bool FlagClienti { get; set; }
        public bool FlagPratiche { get; set; }
        public bool FlagServizi { get; set; }
        public bool FlagFornitori { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clienti> Clienti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fornitori> Fornitori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opportunita> Opportunita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pratiche> Pratiche { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servizi> Servizi { get; set; }
    }
}
