//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SezioniOfferta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SezioniOfferta()
        {
            this.ElementiOfferta = new HashSet<ElementiOfferta>();
            this.OfferteTotaliSezioni = new HashSet<OfferteTotaliSezioni>();
            this.ScaglioniSezioneOfferta = new HashSet<ScaglioniSezioneOfferta>();
        }
    
        public int AnnoPratica { get; set; }
        public int NumPratica { get; set; }
        public short NumOfferta { get; set; }
        public short NumSezione { get; set; }
        public string DescrizioneSezione { get; set; }
        public Nullable<double> PrezzoVendita { get; set; }
        public Nullable<double> SupplSingola { get; set; }
        public bool FlagPrezzoAPacchetto { get; set; }
        public bool IsExtra { get; set; }
        public bool IsNoCommissione { get; set; }
        public Nullable<short> SezioneAlternativa { get; set; }
        public bool IsAttiva { get; set; }
        public Nullable<double> MargineTarget { get; set; }
        public bool FlagDayByDay { get; set; }
        public bool FlagServiziSoloCosto { get; set; }
        public short ProgSezione { get; set; }
        public bool FlagScaglioni { get; set; }
        public string GratuitaID { get; set; }
        public Nullable<short> NumMinPax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementiOfferta> ElementiOfferta { get; set; }
        public virtual Gratuita Gratuita { get; set; }
        public virtual Offerte Offerte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferteTotaliSezioni> OfferteTotaliSezioni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScaglioniSezioneOfferta> ScaglioniSezioneOfferta { get; set; }
    }
}
