//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StringheLingue
    {
        public long idStringa { get; set; }
        public short idLingua { get; set; }
        public string testo { get; set; }
        public bool isOK { get; set; }
        public long ixStringa { get; set; }
    
        public virtual Lingue Lingue { get; set; }
        public virtual Stringhe Stringhe { get; set; }
    }
}
