//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasseSoggiorno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TasseSoggiorno()
        {
            this.Destinazioni = new HashSet<Destinazioni>();
            this.TasseSoggiornoRighe = new HashSet<TasseSoggiornoRighe>();
            this.UsiStringa = new HashSet<UsiStringa>();
        }
    
        public short TassaSoggiornoID { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DataInizioValidita { get; set; }
        public Nullable<long> NoteCliente { get; set; }
        public string NoteInterne { get; set; }
        public bool FlagAutistaGratis { get; set; }
        public string GratuitaBambini { get; set; }
        public Nullable<long> NoteGratuitaCliente { get; set; }
        public string OperUltAgg { get; set; }
        public System.DateTime DataUltAgg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Destinazioni> Destinazioni { get; set; }
        public virtual Operatori Operatori { get; set; }
        public virtual Stringhe Stringhe { get; set; }
        public virtual Stringhe Stringhe1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasseSoggiornoRighe> TasseSoggiornoRighe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsiStringa> UsiStringa { get; set; }
    }
}
