//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipiFornitore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipiFornitore()
        {
            this.Fornitori = new HashSet<Fornitori>();
        }
    
        public short TipoFornitoreID { get; set; }
        public string Descrizione { get; set; }
        public string Categoria { get; set; }
        public string CodTipoFornitoreGo2 { get; set; }
        public bool IsFornitoreAlberghiero { get; set; }
        public bool IsLocalePubblico { get; set; }
        public bool IsGuida { get; set; }
        public bool IsFornitoreTrasporti { get; set; }
        public bool IsAltroTipoForn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fornitori> Fornitori { get; set; }
    }
}
