//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipiCamera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipiCamera()
        {
            this.Camere = new HashSet<Camere>();
            this.ClientiTipiCamera = new HashSet<ClientiTipiCamera>();
            this.ElementiOffertaTipiCamera = new HashSet<ElementiOffertaTipiCamera>();
            this.ElementiOrdineTipiCamera = new HashSet<ElementiOrdineTipiCamera>();
            this.PraticheSistemazioniTipiCamera = new HashSet<PraticheSistemazioniTipiCamera>();
        }
    
        public string CodTipoCamera { get; set; }
        public long Descrizione { get; set; }
        public Nullable<short> NumeroPersone { get; set; }
        public bool FlagOpzione { get; set; }
        public string NomeInterno { get; set; }
        public bool FlagBase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Camere> Camere { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientiTipiCamera> ClientiTipiCamera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementiOffertaTipiCamera> ElementiOffertaTipiCamera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementiOrdineTipiCamera> ElementiOrdineTipiCamera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PraticheSistemazioniTipiCamera> PraticheSistemazioniTipiCamera { get; set; }
        public virtual Stringhe Stringhe { get; set; }
    }
}
