//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipiDocumentoModelli
    {
        public short TipoDocumentoID { get; set; }
        public short ModelloDocumentoID { get; set; }
        public short IdLingua { get; set; }
        public string NomeModello { get; set; }
        public string TemplateEmail { get; set; }
        public string TemplateHtml { get; set; }
        public string TemplateWord { get; set; }
        public bool FlagDefault { get; set; }
    
        public virtual Lingue Lingue { get; set; }
        public virtual TipiDocumento TipiDocumento { get; set; }
    }
}
