//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipiDocumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipiDocumento()
        {
            this.Documenti = new HashSet<Documenti>();
            this.TipiDocumentoModelli = new HashSet<TipiDocumentoModelli>();
        }
    
        public short TipoDocumentoID { get; set; }
        public string TitoloTipoDocumento { get; set; }
        public bool FlagRiferibileAPratica { get; set; }
        public bool FlagRiferibileACliente { get; set; }
        public bool FlagRiferibileAFornitore { get; set; }
        public bool FlagRiferibileADestinazione { get; set; }
        public bool FlagRiferibileAServizio { get; set; }
        public bool FlagRiferibileAElementoOff_ord { get; set; }
        public bool FlagDaNonUsarePiu { get; set; }
        public string PercorsoSalvataggio { get; set; }
        public string Estensione { get; set; }
        public string ProgrammaAperturaDoc { get; set; }
        public string SiglaTipoDoc { get; set; }
        public Nullable<short> StatoPartenza { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documenti> Documenti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipiDocumentoModelli> TipiDocumentoModelli { get; set; }
    }
}
