//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsiStringa
    {
        public long StringaID { get; set; }
        public int UsoStringaID { get; set; }
        public Nullable<int> DestinazioneID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> FornitoreID { get; set; }
        public Nullable<int> ServizioID { get; set; }
        public Nullable<int> Anno { get; set; }
        public Nullable<short> VariantePrezzoID { get; set; }
        public Nullable<short> TassaSoggiornoID { get; set; }
    
        public virtual Clienti Clienti { get; set; }
        public virtual Destinazioni Destinazioni { get; set; }
        public virtual Fornitori Fornitori { get; set; }
        public virtual Servizi Servizi { get; set; }
        public virtual Stringhe Stringhe { get; set; }
        public virtual TasseSoggiorno TasseSoggiorno { get; set; }
        public virtual VariantiPrezziServizioFornitoreAnno VariantiPrezziServizioFornitoreAnno { get; set; }
    }
}
