//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Valute()
        {
            this.Fornitori = new HashSet<Fornitori>();
            this.Nazioni = new HashSet<Nazioni>();
            this.Pratiche = new HashSet<Pratiche>();
        }
    
        public short ValutaId { get; set; }
        public string Descrizione { get; set; }
        public string DescrizioneLingua { get; set; }
        public string DescrizioneCorta { get; set; }
        public short CodiceLingua { get; set; }
        public Nullable<double> CambioEuro { get; set; }
        public Nullable<System.DateTime> DataCambio { get; set; }
        public string CodiceIsoValuta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fornitori> Fornitori { get; set; }
        public virtual Lingue Lingue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nazioni> Nazioni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pratiche> Pratiche { get; set; }
    }
}
