//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariantiPrezziFornitoriAnnoTariffe
    {
        public int FornitoreID { get; set; }
        public int Anno { get; set; }
        public short TariffaID { get; set; }
        public short VariantePrezzoID { get; set; }
        public Nullable<double> PrezzoAcquistoLordo { get; set; }
        public Nullable<double> PrezzoAcquistoScorporatoIva { get; set; }
        public Nullable<double> PrezzoVendita { get; set; }
        public string CondizioniDescrittive { get; set; }
        public Nullable<System.DateTime> DataDa { get; set; }
        public Nullable<System.DateTime> DataA { get; set; }
        public Nullable<short> PaxDa { get; set; }
        public Nullable<short> PaxA { get; set; }
        public string TipoPrezzoAcquisto { get; set; }
        public string TipoPrezzoVendita { get; set; }
        public Nullable<short> PaxLimite { get; set; }
        public Nullable<double> IncrementoUnitarioAcquisto { get; set; }
        public Nullable<double> IncrementoUnitarioVendita { get; set; }
        public Nullable<short> DivisoreAcquisto { get; set; }
        public Nullable<short> DivisoreVendita { get; set; }
        public short AliquotaIva { get; set; }
        public Nullable<double> PercCommissione { get; set; }
        public Nullable<short> AliquotaIvaSuCommissione { get; set; }
        public Nullable<double> CommissioneInEuroLorda { get; set; }
        public Nullable<long> NoteVoucherCliente { get; set; }
        public Nullable<long> NoteVoucherFornitore { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<double> MargineLordo { get; set; }
        public bool FlagDaRipartirePerPax { get; set; }
        public Nullable<int> IDPrezzoGo4 { get; set; }
    }
}
