//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariantiLogisticheServizio
    {
        public int ServizioID { get; set; }
        public int FornitoreID { get; set; }
        public short VarianteLogisticaID { get; set; }
        public Nullable<long> Titolo { get; set; }
        public Nullable<long> DescrizioneTestuale { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<System.TimeSpan> Orario { get; set; }
    
        public virtual Servizi Servizi { get; set; }
        public virtual Stringhe Stringhe { get; set; }
        public virtual Stringhe Stringhe1 { get; set; }
    }
}
