//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Sincro_GO4_Fornitori_SchedePrezziLingue_Aggiornati_Dizionario_Base
    {
        public string RiferimentoStringa { get; set; }
        public short CodiceLingua { get; set; }
        public string NoteVoucherFornitore { get; set; }
        public string NoteVoucherCliente { get; set; }
    }
}
