//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Sincro_Pratiche_Servizi_Connessione
    {
        public Nullable<short> Anno { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<int> Servizio { get; set; }
        public int ServizioID { get; set; }
        public Nullable<int> CodiceFornitore { get; set; }
        public Nullable<int> TipoServizioID { get; set; }
        public Nullable<int> DestinazioneID { get; set; }
        public string DescrizioneAnziano { get; set; }
        public string DescrizioneAnzianoLingua { get; set; }
    }
}
