//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Sincro_Pratiche_ElementiOfferta_DaAggiungere
    {
        public Nullable<short> Anno { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<short> Offerta { get; set; }
        public int NumeroSezione { get; set; }
        public Nullable<int> Servizio { get; set; }
    }
}
