//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Sincro_Pratiche_Servizi_Dettaglio
    {
        public Nullable<short> Anno { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<short> StatoId { get; set; }
        public Nullable<System.DateTime> DataConfermaCliente1Liv { get; set; }
        public Nullable<short> Offerta { get; set; }
        public int NumeroSezione { get; set; }
        public Nullable<int> Servizio { get; set; }
        public string CodiceSequenza { get; set; }
        public string Pacchetto { get; set; }
        public Nullable<int> CodiceFornitore { get; set; }
        public Nullable<int> CodiceTourOperator { get; set; }
        public Nullable<int> CodiceFatturante { get; set; }
        public Nullable<System.DateTime> DataRichiesta { get; set; }
        public Nullable<System.DateTime> DataScadenzaOpzione { get; set; }
        public Nullable<System.DateTime> DataRelease { get; set; }
        public Nullable<System.DateTime> DataNCF { get; set; }
        public Nullable<System.DateTime> DataVCF { get; set; }
        public int ServizioID { get; set; }
        public Nullable<int> TipoServizioID { get; set; }
        public Nullable<int> DestinazioneID { get; set; }
        public int FlagIndirizzo { get; set; }
        public int FlagIndicazioni { get; set; }
        public int FlagDescrizione { get; set; }
        public int FlagChiuso { get; set; }
        public string DescrizioneLocalita { get; set; }
        public string RoomingList { get; set; }
        public string CodiceGratuita { get; set; }
        public Nullable<System.DateTime> DataDal { get; set; }
        public Nullable<System.DateTime> DataAl { get; set; }
        public int Incluso { get; set; }
        public Nullable<short> PaxAcquisto { get; set; }
        public Nullable<short> GratuitaAcquisto { get; set; }
        public Nullable<short> PaxVendita { get; set; }
        public Nullable<short> GratuitaVendita { get; set; }
        public Nullable<decimal> Acquisto { get; set; }
        public Nullable<decimal> AcquistoValuta { get; set; }
        public Nullable<decimal> Vendita { get; set; }
        public Nullable<decimal> VenditaValuta { get; set; }
        public Nullable<decimal> TotaleAcquisto { get; set; }
        public Nullable<decimal> TotaleAcquistoValuta { get; set; }
        public Nullable<decimal> TotaleVendita { get; set; }
        public Nullable<decimal> TotaleVenditaValuta { get; set; }
        public Nullable<short> NumeroVolte { get; set; }
        public Nullable<decimal> PrezzoLordo { get; set; }
        public Nullable<short> AliquotaIVA { get; set; }
        public Nullable<decimal> ImportoScorporatoIVA { get; set; }
        public Nullable<float> PercentualeCommissione { get; set; }
        public Nullable<decimal> CommissioneCalcolata { get; set; }
        public Nullable<decimal> CommissioneManuale { get; set; }
        public Nullable<decimal> PrezzoForfetario { get; set; }
        public Nullable<decimal> Margine { get; set; }
        public Nullable<float> MarginePercentuale { get; set; }
        public string TipoPrezzo { get; set; }
        public Nullable<decimal> TotaleCommissione { get; set; }
        public Nullable<decimal> TotaleCommissioneValuta { get; set; }
        public string EscludiCommissione { get; set; }
        public string MagicBrick { get; set; }
        public Nullable<long> DescrizioneEstesa { get; set; }
        public Nullable<long> NoteVoucherCliente { get; set; }
        public Nullable<long> NoteVoucherFornitore { get; set; }
        public string NoteInterne { get; set; }
        public bool FlagAttivo { get; set; }
        public bool FlagRaggruppamento { get; set; }
        public long Descrizione { get; set; }
        public Nullable<long> NoteVoucher { get; set; }
        public string NotaInterna { get; set; }
        public short IdCategoria { get; set; }
        public string TipoPrezzoAcquisto { get; set; }
        public string TipoPrezzoVendita { get; set; }
        public bool IsInclusoInRicerche { get; set; }
        public bool IsSupplementare { get; set; }
        public bool IsAttivo { get; set; }
        public bool IsDescServizioInOfferta { get; set; }
        public bool IsImgServizioInOfferta { get; set; }
        public bool IsDescFornInOfferta { get; set; }
        public bool IsImgFornInOfferta { get; set; }
        public bool IsDescDestInOfferta { get; set; }
        public bool IsImgDestInOfferta { get; set; }
        public bool FlagDataOpzioneFornitore { get; set; }
        public bool FlagCheckUnGiornoPrima { get; set; }
        public bool FlagAmmetteValutazione { get; set; }
        public bool FlagStampaVoucher { get; set; }
        public bool FlagAmmetteTassaSoggiorno { get; set; }
        public bool FlagNonSoggettaACommissioni { get; set; }
        public bool FlagNecessariaListaNominativa { get; set; }
        public bool FlagNecessarioNumPax { get; set; }
        public bool FlagSoloPerSingola { get; set; }
        public bool FlagNomeFornInDocs { get; set; }
        public bool FlagIndirFornInDocs { get; set; }
        public bool FlagIndicaFornInDocs { get; set; }
        public bool FlagStampaInDayByDay { get; set; }
        public bool FlagZTL { get; set; }
        public string Annotazioni { get; set; }
        public string Voucher { get; set; }
        public string VoucherLingua { get; set; }
        public string Sistemazioni { get; set; }
        public string DescrizioneAnziano { get; set; }
        public string DescrizioneAnzianoLingua { get; set; }
        public int Falso { get; set; }
        public int Vero { get; set; }
    }
}
