//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Sincro_Dizionario_Servizi_NoName_Passo2
    {
        public int TipoServizioID { get; set; }
        public int FornitoreID { get; set; }
        public int DestinazioneID { get; set; }
        public long Stringa { get; set; }
        public string Note { get; set; }
        public string Nome { get; set; }
        public string Identificatore { get; set; }
    }
}
