//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Sincro_Pratiche_DocumentiRicevuti
    {
        public Nullable<short> Anno { get; set; }
        public Nullable<int> Numero { get; set; }
        public int TipoDocumentoID { get; set; }
        public string Percorso { get; set; }
        public string NomeFile { get; set; }
        public string Note { get; set; }
        public int ZeroFalso { get; set; }
        public Nullable<int> CodiceDestinazionePratica { get; set; }
        public string Descrizione { get; set; }
        public Nullable<int> Progressivo { get; set; }
    }
}
