//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GO5_SupplierPreview.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Sincro_attivita_relazioni
    {
        public string GO2CodiceAttivita { get; set; }
        public string Descrizione { get; set; }
        public string GO5CodiceAttivita { get; set; }
        public short TipoIDGO5 { get; set; }
        public short SottoTipoIDGO5 { get; set; }
    }
}
